package tw.msigDvrBack.manual;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tw.msigDvrBack.persistence.TbBatchJobLog;
import tw.msigDvrBack.persistence.TbBatchJobLogExample;

public interface TbBatchJobLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_batch_job_log
     *
     * @mbg.generated Fri Jun 05 13:53:54 CST 2020
     */
    long countByExample(TbBatchJobLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_batch_job_log
     *
     * @mbg.generated Fri Jun 05 13:53:54 CST 2020
     */
    int deleteByExample(TbBatchJobLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_batch_job_log
     *
     * @mbg.generated Fri Jun 05 13:53:54 CST 2020
     */
    int deleteByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_batch_job_log
     *
     * @mbg.generated Fri Jun 05 13:53:54 CST 2020
     */
    int insert(TbBatchJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_batch_job_log
     *
     * @mbg.generated Fri Jun 05 13:53:54 CST 2020
     */
    int insertSelective(TbBatchJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_batch_job_log
     *
     * @mbg.generated Fri Jun 05 13:53:54 CST 2020
     */
    List<TbBatchJobLog> selectByExample(TbBatchJobLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_batch_job_log
     *
     * @mbg.generated Fri Jun 05 13:53:54 CST 2020
     */
    TbBatchJobLog selectByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_batch_job_log
     *
     * @mbg.generated Fri Jun 05 13:53:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") TbBatchJobLog record, @Param("example") TbBatchJobLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_batch_job_log
     *
     * @mbg.generated Fri Jun 05 13:53:54 CST 2020
     */
    int updateByExample(@Param("record") TbBatchJobLog record, @Param("example") TbBatchJobLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_batch_job_log
     *
     * @mbg.generated Fri Jun 05 13:53:54 CST 2020
     */
    int updateByPrimaryKeySelective(TbBatchJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_batch_job_log
     *
     * @mbg.generated Fri Jun 05 13:53:54 CST 2020
     */
    int updateByPrimaryKey(TbBatchJobLog record);
}