package tw.msigDvrBack.manual;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import tw.msigDvrBack.persistence.TbCustomer;
import tw.msigDvrBack.persistence.TbCustomerExample;
import tw.msigDvrBack.persistence.TbSysUser;
import tw.msigDvrBack.persistence.TbSysUserExample;

public interface TbCustomerManualMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated Thu Apr 14 17:18:00 GMT+08:00 2016
     */
    Long countByExample(Map<String,Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated Thu Apr 14 17:18:00 GMT+08:00 2016
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated Thu Apr 14 17:18:00 GMT+08:00 2016
     */
    int insert(TbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated Thu Apr 14 17:18:00 GMT+08:00 2016
     */
    int insertSelective(TbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated Thu Apr 14 17:18:00 GMT+08:00 2016
     */
    List<TbCustomer> selectByExample(Map<String,Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated Thu Apr 14 17:18:00 GMT+08:00 2016
     */
    TbCustomer selectByPrimaryKey(String userId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated Thu Apr 14 17:18:00 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(TbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated Thu Apr 14 17:18:00 GMT+08:00 2016
     */
    int updateByPrimaryKey(TbCustomer record);
    
	int updateByExampleSelective(@Param("record") TbCustomer record, @Param("example") TbCustomerExample example);

    
    
    List<Map<String,Object>> getCustomerAndCustCar(Map<String,Object> map);
    
    List<Map<String,Object>> getCustomerAndCustCar002(Map<String,Object> map);
}