package tw.msigDvrBack.manual;


import tw.msigDvrBack.persistence.TbDevice;
import tw.msigDvrBack.persistence.TbDeviceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import tw.msigDvrBack.persistence.TbDeviceExample;

public interface TbDeviceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_device
	 * @mbg.generated  Fri Jun 05 13:39:52 CST 2020
	 */
	int deleteByPrimaryKey(TbDeviceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_device
	 * @mbg.generated  Fri Jun 05 13:39:52 CST 2020
	 */
	int insert(TbDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_device
	 * @mbg.generated  Fri Jun 05 13:39:52 CST 2020
	 */
	int insertSelective(TbDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_device
	 * @mbg.generated  Fri Jun 05 13:39:52 CST 2020
	 */
	List<TbDevice> selectByExample(TbDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_device
	 * @mbg.generated  Fri Jun 05 13:39:52 CST 2020
	 */
	TbDevice selectByPrimaryKey(TbDeviceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_device
	 * @mbg.generated  Fri Jun 05 13:39:52 CST 2020
	 */
	int updateByPrimaryKeySelective(TbDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_device
	 * @mbg.generated  Fri Jun 05 13:39:52 CST 2020
	 */
	int updateByPrimaryKey(TbDevice record);

	int deleteAll();
}