package tw.msigDvrBack.manual;

import java.util.List;
import java.util.Map;

import tw.msigDvrBack.persistence.TbGfbMsg;

public interface TbGfbMsgManualMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Fri Oct 26 10:47:51 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Fri Oct 26 10:47:51 GMT+08:00 2018
     */
    int insert(TbGfbMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Fri Oct 26 10:47:51 GMT+08:00 2018
     */
    int insertSelective(TbGfbMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Fri Oct 26 10:47:51 GMT+08:00 2018
     */
    List<TbGfbMsg> selectByExample(Map<String,Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Fri Oct 26 10:47:51 GMT+08:00 2018
     */
    TbGfbMsg selectByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Fri Oct 26 10:47:51 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(TbGfbMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Fri Oct 26 10:47:51 GMT+08:00 2018
     */
    int updateByPrimaryKey(TbGfbMsg record);
}