package tw.msigDvrBack.manual;

import java.util.List;
import java.util.Map;

import tw.msigDvrBack.persistence.TbNewsUser;

public interface TbNewsUserManualMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Fri Oct 26 11:19:38 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Fri Oct 26 11:19:38 GMT+08:00 2018
     */
    int insert(TbNewsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Fri Oct 26 11:19:38 GMT+08:00 2018
     */
    int insertSelective(TbNewsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Fri Oct 26 11:19:38 GMT+08:00 2018
     */
    List<TbNewsUser> selectByExample(Map<String,Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Fri Oct 26 11:19:38 GMT+08:00 2018
     */
    TbNewsUser selectByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Fri Oct 26 11:19:38 GMT+08:00 2018
     */
    int updateByExampleSelective(Map<String,Object> updateMap );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Fri Oct 26 11:19:38 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(TbNewsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Fri Oct 26 11:19:38 GMT+08:00 2018
     */
    int updateByPrimaryKey(TbNewsUser record);
    
    int updatePushed();
}