package tw.msigDvrBack.manual;

import java.util.List;
import java.util.Map;

import tw.msigDvrBack.persistence.TbNews;

public interface TbNewsManualMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Fri Oct 26 11:05:18 GMT+08:00 2018
     */
    long countByExample(Map<String, Object> map);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Fri Oct 26 11:05:18 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Fri Oct 26 11:05:18 GMT+08:00 2018
     */
    int insert(TbNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Fri Oct 26 11:05:18 GMT+08:00 2018
     */
    int insertSelective(TbNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Fri Oct 26 11:05:18 GMT+08:00 2018
     */
    List<TbNews> selectByExample(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Fri Oct 26 11:05:18 GMT+08:00 2018
     */
    TbNews selectByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Fri Oct 26 11:05:18 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(TbNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Fri Oct 26 11:05:18 GMT+08:00 2018
     */
    int updateByPrimaryKey(TbNews record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Fri Oct 26 11:05:18 GMT+08:00 2018
     */
    int updatePushStatus(Map<String, Object> map);
    
    
    
}