package tw.msigDvrBack.manual;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tw.msigDvrBack.persistence.TbSysUserPwdHis;
import tw.msigDvrBack.persistence.TbSysUserPwdHisExample;

public interface TbSysUserPwdHisManualMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_pwd_his
     *
     * @mbg.generated Tue Jun 02 09:07:10 GMT+08:00 2020
     */
    long countByExample(TbSysUserPwdHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_pwd_his
     *
     * @mbg.generated Tue Jun 02 09:07:10 GMT+08:00 2020
     */
    int deleteByExample(TbSysUserPwdHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_pwd_his
     *
     * @mbg.generated Tue Jun 02 09:07:10 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_pwd_his
     *
     * @mbg.generated Tue Jun 02 09:07:10 GMT+08:00 2020
     */
    int insert(TbSysUserPwdHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_pwd_his
     *
     * @mbg.generated Tue Jun 02 09:07:10 GMT+08:00 2020
     */
    int insertSelective(TbSysUserPwdHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_pwd_his
     *
     * @mbg.generated Tue Jun 02 09:07:10 GMT+08:00 2020
     */
    List<TbSysUserPwdHis> selectByExample(TbSysUserPwdHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_pwd_his
     *
     * @mbg.generated Tue Jun 02 09:07:10 GMT+08:00 2020
     */
    TbSysUserPwdHis selectByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_pwd_his
     *
     * @mbg.generated Tue Jun 02 09:07:10 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") TbSysUserPwdHis record, @Param("example") TbSysUserPwdHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_pwd_his
     *
     * @mbg.generated Tue Jun 02 09:07:10 GMT+08:00 2020
     */
    int updateByExample(@Param("record") TbSysUserPwdHis record, @Param("example") TbSysUserPwdHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_pwd_his
     *
     * @mbg.generated Tue Jun 02 09:07:10 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(TbSysUserPwdHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_pwd_his
     *
     * @mbg.generated Tue Jun 02 09:07:10 GMT+08:00 2020
     */
    int updateByPrimaryKey(TbSysUserPwdHis record);
}