package tw.msigDvrBack.manual;

import java.util.List;
import java.util.Map;

import tw.msigDvrBack.persistence.TbSysUserRoleMap;
import tw.msigDvrBack.persistence.TbSysUserRoleMapKey;

public interface TbSysUserRoleMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_role_map
     *
     * @mbg.generated Wed Sep 26 11:04:46 CST 2018
     */
    long countByExample(Map<String,Object> querymap);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_role_map
     *
     * @mbg.generated Wed Sep 26 11:04:46 CST 2018
     */
    int deleteByPrimaryKey(TbSysUserRoleMapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_role_map
     *
     * @mbg.generated Wed Sep 26 11:04:46 CST 2018
     */
    int insert(TbSysUserRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_role_map
     *
     * @mbg.generated Wed Sep 26 11:04:46 CST 2018
     */
    int insertSelective(TbSysUserRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_role_map
     *
     * @mbg.generated Wed Sep 26 11:04:46 CST 2018
     */
    List<TbSysUserRoleMap> selectByExample(Map<String,Object> querymap );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_role_map
     *
     * @mbg.generated Wed Sep 26 11:04:46 CST 2018
     */
    TbSysUserRoleMap selectByPrimaryKey(TbSysUserRoleMapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_role_map
     *
     * @mbg.generated Wed Sep 26 11:04:46 CST 2018
     */
    int updateByPrimaryKeySelective(TbSysUserRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user_role_map
     *
     * @mbg.generated Wed Sep 26 11:04:46 CST 2018
     */
    int updateByPrimaryKey(TbSysUserRoleMap record);
}