package tw.msigDvrBack.manual;

import java.util.List;
import java.util.Map;

import tw.msigDvrBack.persistence.TbSysMod;

public interface TbSysModMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_mod
	 * @mbggenerated  Thu Aug 20 16:03:23 CST 2015
	 */
	int countByExample(Map<String,Object> querymap );

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_mod
	 * @mbggenerated  Thu Aug 20 16:03:23 CST 2015
	 */
	int deleteByPrimaryKey(String pgProjId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_mod
	 * @mbggenerated  Thu Aug 20 16:03:23 CST 2015
	 */
	int insert(TbSysMod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_mod
	 * @mbggenerated  Thu Aug 20 16:03:23 CST 2015
	 */
	int insertSelective(TbSysMod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_mod
	 * @mbggenerated  Thu Aug 20 16:03:23 CST 2015
	 */
	List<TbSysMod> selectByExample(Map<String, Object> map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_mod
	 * @mbggenerated  Thu Aug 20 16:03:23 CST 2015
	 */
	TbSysMod selectByPrimaryKey(String pgProjId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_mod
	 * @mbggenerated  Thu Aug 20 16:03:23 CST 2015
	 */
	int updateByPrimaryKeySelective(TbSysMod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_mod
	 * @mbggenerated  Thu Aug 20 16:03:23 CST 2015
	 */
	int updateByPrimaryKey(TbSysMod record);
}