package tw.msigDvrBack.manual;

import java.util.List;
import java.util.Map;

import tw.msigDvrBack.persistence.TbWelcomePage;

public interface TbWelcomePageManualMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_welcome_page
     *
     * @mbg.generated Mon Oct 22 15:24:14 GMT+08:00 2018
     */
    long countByExample(Map<String,Object> querymap);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_welcome_page
     *
     * @mbg.generated Mon Oct 22 15:24:14 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String pageType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_welcome_page
     *
     * @mbg.generated Mon Oct 22 15:24:14 GMT+08:00 2018
     */
    int insert(TbWelcomePage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_welcome_page
     *
     * @mbg.generated Mon Oct 22 15:24:14 GMT+08:00 2018
     */
    int insertSelective(TbWelcomePage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_welcome_page
     *
     * @mbg.generated Mon Oct 22 15:24:14 GMT+08:00 2018
     */
    List<TbWelcomePage> selectByExample(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_welcome_page
     *
     * @mbg.generated Mon Oct 22 15:24:14 GMT+08:00 2018
     */
    TbWelcomePage selectByPrimaryKey(String pageType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_welcome_page
     *
     * @mbg.generated Mon Oct 22 15:24:14 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(TbWelcomePage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_welcome_page
     *
     * @mbg.generated Mon Oct 22 15:24:14 GMT+08:00 2018
     */
    int updateByPrimaryKey(TbWelcomePage record);
}