package tw.msigDvrBack.manual;

import java.util.List;
import java.util.Map;

import tw.msigDvrBack.persistence.VwCustCar;


public interface VwCustCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_cust_car
     *
     * @mbg.generated Wed Oct 24 10:23:58 GMT+08:00 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_cust_car
     *
     * @mbg.generated Wed Oct 24 10:23:58 GMT+08:00 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_cust_car
     *
     * @mbg.generated Wed Oct 24 10:23:58 GMT+08:00 2018
     */
    int insert(VwCustCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_cust_car
     *
     * @mbg.generated Wed Oct 24 10:23:58 GMT+08:00 2018
     */
    int insertSelective(VwCustCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_cust_car
     *
     * @mbg.generated Wed Oct 24 10:23:58 GMT+08:00 2018
     */

    
//    List<VwCustCar> selectByEndUbiDate(Date endUbiDate);
    List<VwCustCar> selectByEndUbiDate(Map<String, Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_cust_car
     *
     * @mbg.generated Wed Oct 24 10:23:58 GMT+08:00 2018
     */
  

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_cust_car
     *
     * @mbg.generated Wed Oct 24 10:23:58 GMT+08:00 2018
     */
   
}