package tw.msigDvrBack.manual;

import java.util.List;
import java.util.Map;

import tw.msigDvrBack.persistence.VwCustUbiApply;

public interface VwCustUbiApplyManualMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_cust_ubi_apply
     *
     * @mbg.generated Fri Nov 02 17:28:20 GMT+08:00 2018
     */
    long countByExample(Map<String, Object> map);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_cust_ubi_apply
     *
     * @mbg.generated Fri Nov 02 17:28:20 GMT+08:00 2018
     */
    int insert(VwCustUbiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_cust_ubi_apply
     *
     * @mbg.generated Fri Nov 02 17:28:20 GMT+08:00 2018
     */
    int insertSelective(VwCustUbiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_cust_ubi_apply
     *
     * @mbg.generated Fri Nov 02 17:28:20 GMT+08:00 2018
     */
    List<VwCustUbiApply> selectByExample(Map<String, Object> map);

}