package tw.msigDvrBack.manual;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import tw.msigDvrBack.persistence.VwCustomer;


public interface VwCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_customer
     *
     * @mbg.generated Tue Oct 23 14:49:04 GMT+08:00 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_customer
     *
     * @mbg.generated Tue Oct 23 14:49:04 GMT+08:00 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_customer
     *
     * @mbg.generated Tue Oct 23 14:49:04 GMT+08:00 2018
     */
    int insert(VwCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_customer
     *
     * @mbg.generated Tue Oct 23 14:49:04 GMT+08:00 2018
     */
    int insertSelective(VwCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_customer
     *
     * @mbg.generated Tue Oct 23 14:49:04 GMT+08:00 2018
     */

    
//    List<VwCustomer> SelectByAppLoginTime(Date appLoginTime);
    List<VwCustomer> SelectByAppLoginTime(Map<String,Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_customer
     *
     * @mbg.generated Tue Oct 23 14:49:04 GMT+08:00 2018
     */
  

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_customer
     *
     * @mbg.generated Tue Oct 23 14:49:04 GMT+08:00 2018
     */
   
}