package tw.msigDvrBack.manual;

import java.util.List;
import java.util.Map;

import tw.msigDvrBack.persistence.VwNewsuserCustcar;

public interface VwNewsuserCustcarManualMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_newsuser_custcar
     *
     * @mbg.generated Mon Oct 29 08:50:56 GMT+08:00 2018
     */
    int insert(VwNewsuserCustcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_newsuser_custcar
     *
     * @mbg.generated Mon Oct 29 08:50:56 GMT+08:00 2018
     */
    int insertSelective(VwNewsuserCustcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_newsuser_custcar
     *
     * @mbg.generated Mon Oct 29 08:50:56 GMT+08:00 2018
     */
    List<VwNewsuserCustcar> selectByExample(Map<String,Object> querymap);

}