package tw.msigDvrBack.mapper;


import tw.msigDvrBack.persistence.TbGfbMsg;


public interface TbGfbMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
 

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    int insert(TbGfbMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    int insertSelective(TbGfbMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    TbGfbMsg selectByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(TbGfbMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    int updateByPrimaryKey(TbGfbMsg record);
}