package tw.msigDvrBack.mapper;


import java.util.Map;

import tw.msigDvrBack.persistence.TbNewsUser;


public interface TbNewsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Wed Oct 24 12:10:20 GMT+08:00 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Wed Oct 24 12:10:20 GMT+08:00 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Wed Oct 24 12:10:20 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Wed Oct 24 12:10:20 GMT+08:00 2018
     */
    int insert(TbNewsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Wed Oct 24 12:10:20 GMT+08:00 2018
     */
    int insertSelective(TbNewsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Wed Oct 24 12:10:20 GMT+08:00 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Wed Oct 24 12:10:20 GMT+08:00 2018
     */
    TbNewsUser selectByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Wed Oct 24 12:10:20 GMT+08:00 2018
     */
  

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Wed Oct 24 12:10:20 GMT+08:00 2018
     */
   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Wed Oct 24 12:10:20 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(TbNewsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news_user
     *
     * @mbg.generated Wed Oct 24 12:10:20 GMT+08:00 2018
     */
    int updateByPrimaryKey(TbNewsUser record);
    
	/**
	 * <pre>
	 * Method Name : updateStatusBySeqNo
	 * Description : 因應弱點掃描修改的方法
	 * 
	 * </pre>
	 * @since 2018/11/15
	 * @author Jerry
	 * 
	 * @param map
	 * @return list
	 */
    int updateStatusBySeqNo(Map<String, Object> map);

    
}