package tw.msigDvrBack.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import tw.msigDvrBack.persistence.TbNews;


public interface TbNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Oct 24 11:38:04 GMT+08:00 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Oct 24 11:38:04 GMT+08:00 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Oct 24 11:38:04 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Oct 24 11:38:04 GMT+08:00 2018
     */
    int insert(TbNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Oct 24 11:38:04 GMT+08:00 2018
     */
    int insertSelective(TbNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Oct 24 11:38:04 GMT+08:00 2018
     */

    /**
	 * <pre>
	 * Method Name : selectByExample
	 * Description : 因應弱點掃描修改的方法
	 * 
	 * </pre>
	 * @since 2018/11/22
	 * @author Jerry
	 * 
	 * @param map
	 * @return list
	 */
	 List<TbNews> selectByExampleManual(Map<String, Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Oct 24 11:38:04 GMT+08:00 2018
     */
    TbNews selectByPrimaryKey(Integer seqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Oct 24 11:38:04 GMT+08:00 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Oct 24 11:38:04 GMT+08:00 2018
     */
 

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Oct 24 11:38:04 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(TbNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Wed Oct 24 11:38:04 GMT+08:00 2018
     */
    int updateByPrimaryKey(TbNews record);
}