package tw.msigDvrBack.persistence;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TbCustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    public TbCustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andEngNameIsNull() {
            addCriterion("eng_name is null");
            return (Criteria) this;
        }

        public Criteria andEngNameIsNotNull() {
            addCriterion("eng_name is not null");
            return (Criteria) this;
        }

        public Criteria andEngNameEqualTo(String value) {
            addCriterion("eng_name =", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameNotEqualTo(String value) {
            addCriterion("eng_name <>", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameGreaterThan(String value) {
            addCriterion("eng_name >", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameGreaterThanOrEqualTo(String value) {
            addCriterion("eng_name >=", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameLessThan(String value) {
            addCriterion("eng_name <", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameLessThanOrEqualTo(String value) {
            addCriterion("eng_name <=", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameLike(String value) {
            addCriterion("eng_name like", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameNotLike(String value) {
            addCriterion("eng_name not like", value, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameIn(List<String> values) {
            addCriterion("eng_name in", values, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameNotIn(List<String> values) {
            addCriterion("eng_name not in", values, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameBetween(String value1, String value2) {
            addCriterion("eng_name between", value1, value2, "engName");
            return (Criteria) this;
        }

        public Criteria andEngNameNotBetween(String value1, String value2) {
            addCriterion("eng_name not between", value1, value2, "engName");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNull() {
            addCriterion("mobile_phone is null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNotNull() {
            addCriterion("mobile_phone is not null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneEqualTo(String value) {
            addCriterion("mobile_phone =", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotEqualTo(String value) {
            addCriterion("mobile_phone <>", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThan(String value) {
            addCriterion("mobile_phone >", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_phone >=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThan(String value) {
            addCriterion("mobile_phone <", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThanOrEqualTo(String value) {
            addCriterion("mobile_phone <=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLike(String value) {
            addCriterion("mobile_phone like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotLike(String value) {
            addCriterion("mobile_phone not like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIn(List<String> values) {
            addCriterion("mobile_phone in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotIn(List<String> values) {
            addCriterion("mobile_phone not in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneBetween(String value1, String value2) {
            addCriterion("mobile_phone between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotBetween(String value1, String value2) {
            addCriterion("mobile_phone not between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andDobIsNull() {
            addCriterion("dob is null");
            return (Criteria) this;
        }

        public Criteria andDobIsNotNull() {
            addCriterion("dob is not null");
            return (Criteria) this;
        }

        public Criteria andDobEqualTo(Date value) {
            addCriterionForJDBCDate("dob =", value, "dob");
            return (Criteria) this;
        }

        public Criteria andDobNotEqualTo(Date value) {
            addCriterionForJDBCDate("dob <>", value, "dob");
            return (Criteria) this;
        }

        public Criteria andDobGreaterThan(Date value) {
            addCriterionForJDBCDate("dob >", value, "dob");
            return (Criteria) this;
        }

        public Criteria andDobGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("dob >=", value, "dob");
            return (Criteria) this;
        }

        public Criteria andDobLessThan(Date value) {
            addCriterionForJDBCDate("dob <", value, "dob");
            return (Criteria) this;
        }

        public Criteria andDobLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("dob <=", value, "dob");
            return (Criteria) this;
        }

        public Criteria andDobIn(List<Date> values) {
            addCriterionForJDBCDate("dob in", values, "dob");
            return (Criteria) this;
        }

        public Criteria andDobNotIn(List<Date> values) {
            addCriterionForJDBCDate("dob not in", values, "dob");
            return (Criteria) this;
        }

        public Criteria andDobBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("dob between", value1, value2, "dob");
            return (Criteria) this;
        }

        public Criteria andDobNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("dob not between", value1, value2, "dob");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIsNull() {
            addCriterion("contact_phone is null");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIsNotNull() {
            addCriterion("contact_phone is not null");
            return (Criteria) this;
        }

        public Criteria andContactPhoneEqualTo(String value) {
            addCriterion("contact_phone =", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotEqualTo(String value) {
            addCriterion("contact_phone <>", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneGreaterThan(String value) {
            addCriterion("contact_phone >", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("contact_phone >=", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLessThan(String value) {
            addCriterion("contact_phone <", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLessThanOrEqualTo(String value) {
            addCriterion("contact_phone <=", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLike(String value) {
            addCriterion("contact_phone like", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotLike(String value) {
            addCriterion("contact_phone not like", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIn(List<String> values) {
            addCriterion("contact_phone in", values, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotIn(List<String> values) {
            addCriterion("contact_phone not in", values, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneBetween(String value1, String value2) {
            addCriterion("contact_phone between", value1, value2, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotBetween(String value1, String value2) {
            addCriterion("contact_phone not between", value1, value2, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andAddrIsNull() {
            addCriterion("addr is null");
            return (Criteria) this;
        }

        public Criteria andAddrIsNotNull() {
            addCriterion("addr is not null");
            return (Criteria) this;
        }

        public Criteria andAddrEqualTo(String value) {
            addCriterion("addr =", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotEqualTo(String value) {
            addCriterion("addr <>", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrGreaterThan(String value) {
            addCriterion("addr >", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrGreaterThanOrEqualTo(String value) {
            addCriterion("addr >=", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLessThan(String value) {
            addCriterion("addr <", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLessThanOrEqualTo(String value) {
            addCriterion("addr <=", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLike(String value) {
            addCriterion("addr like", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotLike(String value) {
            addCriterion("addr not like", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrIn(List<String> values) {
            addCriterion("addr in", values, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotIn(List<String> values) {
            addCriterion("addr not in", values, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrBetween(String value1, String value2) {
            addCriterion("addr between", value1, value2, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotBetween(String value1, String value2) {
            addCriterion("addr not between", value1, value2, "addr");
            return (Criteria) this;
        }

        public Criteria andCustStatusIsNull() {
            addCriterion("cust_status is null");
            return (Criteria) this;
        }

        public Criteria andCustStatusIsNotNull() {
            addCriterion("cust_status is not null");
            return (Criteria) this;
        }

        public Criteria andCustStatusEqualTo(String value) {
            addCriterion("cust_status =", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusNotEqualTo(String value) {
            addCriterion("cust_status <>", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusGreaterThan(String value) {
            addCriterion("cust_status >", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusGreaterThanOrEqualTo(String value) {
            addCriterion("cust_status >=", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusLessThan(String value) {
            addCriterion("cust_status <", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusLessThanOrEqualTo(String value) {
            addCriterion("cust_status <=", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusLike(String value) {
            addCriterion("cust_status like", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusNotLike(String value) {
            addCriterion("cust_status not like", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusIn(List<String> values) {
            addCriterion("cust_status in", values, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusNotIn(List<String> values) {
            addCriterion("cust_status not in", values, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusBetween(String value1, String value2) {
            addCriterion("cust_status between", value1, value2, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusNotBetween(String value1, String value2) {
            addCriterion("cust_status not between", value1, value2, "custStatus");
            return (Criteria) this;
        }

        public Criteria andPicUrlIsNull() {
            addCriterion("pic_url is null");
            return (Criteria) this;
        }

        public Criteria andPicUrlIsNotNull() {
            addCriterion("pic_url is not null");
            return (Criteria) this;
        }

        public Criteria andPicUrlEqualTo(String value) {
            addCriterion("pic_url =", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotEqualTo(String value) {
            addCriterion("pic_url <>", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlGreaterThan(String value) {
            addCriterion("pic_url >", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("pic_url >=", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLessThan(String value) {
            addCriterion("pic_url <", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLessThanOrEqualTo(String value) {
            addCriterion("pic_url <=", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLike(String value) {
            addCriterion("pic_url like", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotLike(String value) {
            addCriterion("pic_url not like", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlIn(List<String> values) {
            addCriterion("pic_url in", values, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotIn(List<String> values) {
            addCriterion("pic_url not in", values, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlBetween(String value1, String value2) {
            addCriterion("pic_url between", value1, value2, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotBetween(String value1, String value2) {
            addCriterion("pic_url not between", value1, value2, "picUrl");
            return (Criteria) this;
        }

        public Criteria andCuidIsNull() {
            addCriterion("cuid is null");
            return (Criteria) this;
        }

        public Criteria andCuidIsNotNull() {
            addCriterion("cuid is not null");
            return (Criteria) this;
        }

        public Criteria andCuidEqualTo(String value) {
            addCriterion("cuid =", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidNotEqualTo(String value) {
            addCriterion("cuid <>", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidGreaterThan(String value) {
            addCriterion("cuid >", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidGreaterThanOrEqualTo(String value) {
            addCriterion("cuid >=", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidLessThan(String value) {
            addCriterion("cuid <", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidLessThanOrEqualTo(String value) {
            addCriterion("cuid <=", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidLike(String value) {
            addCriterion("cuid like", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidNotLike(String value) {
            addCriterion("cuid not like", value, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidIn(List<String> values) {
            addCriterion("cuid in", values, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidNotIn(List<String> values) {
            addCriterion("cuid not in", values, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidBetween(String value1, String value2) {
            addCriterion("cuid between", value1, value2, "cuid");
            return (Criteria) this;
        }

        public Criteria andCuidNotBetween(String value1, String value2) {
            addCriterion("cuid not between", value1, value2, "cuid");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeIsNull() {
            addCriterion("agree_time is null");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeIsNotNull() {
            addCriterion("agree_time is not null");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeEqualTo(Date value) {
            addCriterion("agree_time =", value, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeNotEqualTo(Date value) {
            addCriterion("agree_time <>", value, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeGreaterThan(Date value) {
            addCriterion("agree_time >", value, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("agree_time >=", value, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeLessThan(Date value) {
            addCriterion("agree_time <", value, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeLessThanOrEqualTo(Date value) {
            addCriterion("agree_time <=", value, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeIn(List<Date> values) {
            addCriterion("agree_time in", values, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeNotIn(List<Date> values) {
            addCriterion("agree_time not in", values, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeBetween(Date value1, Date value2) {
            addCriterion("agree_time between", value1, value2, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAgreeTimeNotBetween(Date value1, Date value2) {
            addCriterion("agree_time not between", value1, value2, "agreeTime");
            return (Criteria) this;
        }

        public Criteria andAccCtcNameIsNull() {
            addCriterion("acc_ctc_name is null");
            return (Criteria) this;
        }

        public Criteria andAccCtcNameIsNotNull() {
            addCriterion("acc_ctc_name is not null");
            return (Criteria) this;
        }

        public Criteria andAccCtcNameEqualTo(String value) {
            addCriterion("acc_ctc_name =", value, "accCtcName");
            return (Criteria) this;
        }

        public Criteria andAccCtcNameNotEqualTo(String value) {
            addCriterion("acc_ctc_name <>", value, "accCtcName");
            return (Criteria) this;
        }

        public Criteria andAccCtcNameGreaterThan(String value) {
            addCriterion("acc_ctc_name >", value, "accCtcName");
            return (Criteria) this;
        }

        public Criteria andAccCtcNameGreaterThanOrEqualTo(String value) {
            addCriterion("acc_ctc_name >=", value, "accCtcName");
            return (Criteria) this;
        }

        public Criteria andAccCtcNameLessThan(String value) {
            addCriterion("acc_ctc_name <", value, "accCtcName");
            return (Criteria) this;
        }

        public Criteria andAccCtcNameLessThanOrEqualTo(String value) {
            addCriterion("acc_ctc_name <=", value, "accCtcName");
            return (Criteria) this;
        }

        public Criteria andAccCtcNameLike(String value) {
            addCriterion("acc_ctc_name like", value, "accCtcName");
            return (Criteria) this;
        }

        public Criteria andAccCtcNameNotLike(String value) {
            addCriterion("acc_ctc_name not like", value, "accCtcName");
            return (Criteria) this;
        }

        public Criteria andAccCtcNameIn(List<String> values) {
            addCriterion("acc_ctc_name in", values, "accCtcName");
            return (Criteria) this;
        }

        public Criteria andAccCtcNameNotIn(List<String> values) {
            addCriterion("acc_ctc_name not in", values, "accCtcName");
            return (Criteria) this;
        }

        public Criteria andAccCtcNameBetween(String value1, String value2) {
            addCriterion("acc_ctc_name between", value1, value2, "accCtcName");
            return (Criteria) this;
        }

        public Criteria andAccCtcNameNotBetween(String value1, String value2) {
            addCriterion("acc_ctc_name not between", value1, value2, "accCtcName");
            return (Criteria) this;
        }

        public Criteria andAccCtcMobileIsNull() {
            addCriterion("acc_ctc_mobile is null");
            return (Criteria) this;
        }

        public Criteria andAccCtcMobileIsNotNull() {
            addCriterion("acc_ctc_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andAccCtcMobileEqualTo(String value) {
            addCriterion("acc_ctc_mobile =", value, "accCtcMobile");
            return (Criteria) this;
        }

        public Criteria andAccCtcMobileNotEqualTo(String value) {
            addCriterion("acc_ctc_mobile <>", value, "accCtcMobile");
            return (Criteria) this;
        }

        public Criteria andAccCtcMobileGreaterThan(String value) {
            addCriterion("acc_ctc_mobile >", value, "accCtcMobile");
            return (Criteria) this;
        }

        public Criteria andAccCtcMobileGreaterThanOrEqualTo(String value) {
            addCriterion("acc_ctc_mobile >=", value, "accCtcMobile");
            return (Criteria) this;
        }

        public Criteria andAccCtcMobileLessThan(String value) {
            addCriterion("acc_ctc_mobile <", value, "accCtcMobile");
            return (Criteria) this;
        }

        public Criteria andAccCtcMobileLessThanOrEqualTo(String value) {
            addCriterion("acc_ctc_mobile <=", value, "accCtcMobile");
            return (Criteria) this;
        }

        public Criteria andAccCtcMobileLike(String value) {
            addCriterion("acc_ctc_mobile like", value, "accCtcMobile");
            return (Criteria) this;
        }

        public Criteria andAccCtcMobileNotLike(String value) {
            addCriterion("acc_ctc_mobile not like", value, "accCtcMobile");
            return (Criteria) this;
        }

        public Criteria andAccCtcMobileIn(List<String> values) {
            addCriterion("acc_ctc_mobile in", values, "accCtcMobile");
            return (Criteria) this;
        }

        public Criteria andAccCtcMobileNotIn(List<String> values) {
            addCriterion("acc_ctc_mobile not in", values, "accCtcMobile");
            return (Criteria) this;
        }

        public Criteria andAccCtcMobileBetween(String value1, String value2) {
            addCriterion("acc_ctc_mobile between", value1, value2, "accCtcMobile");
            return (Criteria) this;
        }

        public Criteria andAccCtcMobileNotBetween(String value1, String value2) {
            addCriterion("acc_ctc_mobile not between", value1, value2, "accCtcMobile");
            return (Criteria) this;
        }

        public Criteria andPwdStatusIsNull() {
            addCriterion("pwd_status is null");
            return (Criteria) this;
        }

        public Criteria andPwdStatusIsNotNull() {
            addCriterion("pwd_status is not null");
            return (Criteria) this;
        }

        public Criteria andPwdStatusEqualTo(String value) {
            addCriterion("pwd_status =", value, "pwdStatus");
            return (Criteria) this;
        }

        public Criteria andPwdStatusNotEqualTo(String value) {
            addCriterion("pwd_status <>", value, "pwdStatus");
            return (Criteria) this;
        }

        public Criteria andPwdStatusGreaterThan(String value) {
            addCriterion("pwd_status >", value, "pwdStatus");
            return (Criteria) this;
        }

        public Criteria andPwdStatusGreaterThanOrEqualTo(String value) {
            addCriterion("pwd_status >=", value, "pwdStatus");
            return (Criteria) this;
        }

        public Criteria andPwdStatusLessThan(String value) {
            addCriterion("pwd_status <", value, "pwdStatus");
            return (Criteria) this;
        }

        public Criteria andPwdStatusLessThanOrEqualTo(String value) {
            addCriterion("pwd_status <=", value, "pwdStatus");
            return (Criteria) this;
        }

        public Criteria andPwdStatusLike(String value) {
            addCriterion("pwd_status like", value, "pwdStatus");
            return (Criteria) this;
        }

        public Criteria andPwdStatusNotLike(String value) {
            addCriterion("pwd_status not like", value, "pwdStatus");
            return (Criteria) this;
        }

        public Criteria andPwdStatusIn(List<String> values) {
            addCriterion("pwd_status in", values, "pwdStatus");
            return (Criteria) this;
        }

        public Criteria andPwdStatusNotIn(List<String> values) {
            addCriterion("pwd_status not in", values, "pwdStatus");
            return (Criteria) this;
        }

        public Criteria andPwdStatusBetween(String value1, String value2) {
            addCriterion("pwd_status between", value1, value2, "pwdStatus");
            return (Criteria) this;
        }

        public Criteria andPwdStatusNotBetween(String value1, String value2) {
            addCriterion("pwd_status not between", value1, value2, "pwdStatus");
            return (Criteria) this;
        }

        public Criteria andAppLoginTimeIsNull() {
            addCriterion("app_login_time is null");
            return (Criteria) this;
        }

        public Criteria andAppLoginTimeIsNotNull() {
            addCriterion("app_login_time is not null");
            return (Criteria) this;
        }

        public Criteria andAppLoginTimeEqualTo(Date value) {
            addCriterion("app_login_time =", value, "appLoginTime");
            return (Criteria) this;
        }

        public Criteria andAppLoginTimeNotEqualTo(Date value) {
            addCriterion("app_login_time <>", value, "appLoginTime");
            return (Criteria) this;
        }

        public Criteria andAppLoginTimeGreaterThan(Date value) {
            addCriterion("app_login_time >", value, "appLoginTime");
            return (Criteria) this;
        }

        public Criteria andAppLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("app_login_time >=", value, "appLoginTime");
            return (Criteria) this;
        }

        public Criteria andAppLoginTimeLessThan(Date value) {
            addCriterion("app_login_time <", value, "appLoginTime");
            return (Criteria) this;
        }

        public Criteria andAppLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("app_login_time <=", value, "appLoginTime");
            return (Criteria) this;
        }

        public Criteria andAppLoginTimeIn(List<Date> values) {
            addCriterion("app_login_time in", values, "appLoginTime");
            return (Criteria) this;
        }

        public Criteria andAppLoginTimeNotIn(List<Date> values) {
            addCriterion("app_login_time not in", values, "appLoginTime");
            return (Criteria) this;
        }

        public Criteria andAppLoginTimeBetween(Date value1, Date value2) {
            addCriterion("app_login_time between", value1, value2, "appLoginTime");
            return (Criteria) this;
        }

        public Criteria andAppLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("app_login_time not between", value1, value2, "appLoginTime");
            return (Criteria) this;
        }

        public Criteria andCrUserIsNull() {
            addCriterion("cr_user is null");
            return (Criteria) this;
        }

        public Criteria andCrUserIsNotNull() {
            addCriterion("cr_user is not null");
            return (Criteria) this;
        }

        public Criteria andCrUserEqualTo(String value) {
            addCriterion("cr_user =", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserNotEqualTo(String value) {
            addCriterion("cr_user <>", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserGreaterThan(String value) {
            addCriterion("cr_user >", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserGreaterThanOrEqualTo(String value) {
            addCriterion("cr_user >=", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserLessThan(String value) {
            addCriterion("cr_user <", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserLessThanOrEqualTo(String value) {
            addCriterion("cr_user <=", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserLike(String value) {
            addCriterion("cr_user like", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserNotLike(String value) {
            addCriterion("cr_user not like", value, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserIn(List<String> values) {
            addCriterion("cr_user in", values, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserNotIn(List<String> values) {
            addCriterion("cr_user not in", values, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserBetween(String value1, String value2) {
            addCriterion("cr_user between", value1, value2, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrUserNotBetween(String value1, String value2) {
            addCriterion("cr_user not between", value1, value2, "crUser");
            return (Criteria) this;
        }

        public Criteria andCrDateIsNull() {
            addCriterion("cr_date is null");
            return (Criteria) this;
        }

        public Criteria andCrDateIsNotNull() {
            addCriterion("cr_date is not null");
            return (Criteria) this;
        }

        public Criteria andCrDateEqualTo(Date value) {
            addCriterion("cr_date =", value, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateNotEqualTo(Date value) {
            addCriterion("cr_date <>", value, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateGreaterThan(Date value) {
            addCriterion("cr_date >", value, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateGreaterThanOrEqualTo(Date value) {
            addCriterion("cr_date >=", value, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateLessThan(Date value) {
            addCriterion("cr_date <", value, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateLessThanOrEqualTo(Date value) {
            addCriterion("cr_date <=", value, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateIn(List<Date> values) {
            addCriterion("cr_date in", values, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateNotIn(List<Date> values) {
            addCriterion("cr_date not in", values, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateBetween(Date value1, Date value2) {
            addCriterion("cr_date between", value1, value2, "crDate");
            return (Criteria) this;
        }

        public Criteria andCrDateNotBetween(Date value1, Date value2) {
            addCriterion("cr_date not between", value1, value2, "crDate");
            return (Criteria) this;
        }

        public Criteria andUserstampIsNull() {
            addCriterion("userstamp is null");
            return (Criteria) this;
        }

        public Criteria andUserstampIsNotNull() {
            addCriterion("userstamp is not null");
            return (Criteria) this;
        }

        public Criteria andUserstampEqualTo(String value) {
            addCriterion("userstamp =", value, "userstamp");
            return (Criteria) this;
        }

        public Criteria andUserstampNotEqualTo(String value) {
            addCriterion("userstamp <>", value, "userstamp");
            return (Criteria) this;
        }

        public Criteria andUserstampGreaterThan(String value) {
            addCriterion("userstamp >", value, "userstamp");
            return (Criteria) this;
        }

        public Criteria andUserstampGreaterThanOrEqualTo(String value) {
            addCriterion("userstamp >=", value, "userstamp");
            return (Criteria) this;
        }

        public Criteria andUserstampLessThan(String value) {
            addCriterion("userstamp <", value, "userstamp");
            return (Criteria) this;
        }

        public Criteria andUserstampLessThanOrEqualTo(String value) {
            addCriterion("userstamp <=", value, "userstamp");
            return (Criteria) this;
        }

        public Criteria andUserstampLike(String value) {
            addCriterion("userstamp like", value, "userstamp");
            return (Criteria) this;
        }

        public Criteria andUserstampNotLike(String value) {
            addCriterion("userstamp not like", value, "userstamp");
            return (Criteria) this;
        }

        public Criteria andUserstampIn(List<String> values) {
            addCriterion("userstamp in", values, "userstamp");
            return (Criteria) this;
        }

        public Criteria andUserstampNotIn(List<String> values) {
            addCriterion("userstamp not in", values, "userstamp");
            return (Criteria) this;
        }

        public Criteria andUserstampBetween(String value1, String value2) {
            addCriterion("userstamp between", value1, value2, "userstamp");
            return (Criteria) this;
        }

        public Criteria andUserstampNotBetween(String value1, String value2) {
            addCriterion("userstamp not between", value1, value2, "userstamp");
            return (Criteria) this;
        }

        public Criteria andDatestampIsNull() {
            addCriterion("datestamp is null");
            return (Criteria) this;
        }

        public Criteria andDatestampIsNotNull() {
            addCriterion("datestamp is not null");
            return (Criteria) this;
        }

        public Criteria andDatestampEqualTo(Date value) {
            addCriterion("datestamp =", value, "datestamp");
            return (Criteria) this;
        }

        public Criteria andDatestampNotEqualTo(Date value) {
            addCriterion("datestamp <>", value, "datestamp");
            return (Criteria) this;
        }

        public Criteria andDatestampGreaterThan(Date value) {
            addCriterion("datestamp >", value, "datestamp");
            return (Criteria) this;
        }

        public Criteria andDatestampGreaterThanOrEqualTo(Date value) {
            addCriterion("datestamp >=", value, "datestamp");
            return (Criteria) this;
        }

        public Criteria andDatestampLessThan(Date value) {
            addCriterion("datestamp <", value, "datestamp");
            return (Criteria) this;
        }

        public Criteria andDatestampLessThanOrEqualTo(Date value) {
            addCriterion("datestamp <=", value, "datestamp");
            return (Criteria) this;
        }

        public Criteria andDatestampIn(List<Date> values) {
            addCriterion("datestamp in", values, "datestamp");
            return (Criteria) this;
        }

        public Criteria andDatestampNotIn(List<Date> values) {
            addCriterion("datestamp not in", values, "datestamp");
            return (Criteria) this;
        }

        public Criteria andDatestampBetween(Date value1, Date value2) {
            addCriterion("datestamp between", value1, value2, "datestamp");
            return (Criteria) this;
        }

        public Criteria andDatestampNotBetween(Date value1, Date value2) {
            addCriterion("datestamp not between", value1, value2, "datestamp");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNull() {
            addCriterion("register_time is null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNotNull() {
            addCriterion("register_time is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeEqualTo(Date value) {
            addCriterion("register_time =", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotEqualTo(Date value) {
            addCriterion("register_time <>", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThan(Date value) {
            addCriterion("register_time >", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("register_time >=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThan(Date value) {
            addCriterion("register_time <", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThanOrEqualTo(Date value) {
            addCriterion("register_time <=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIn(List<Date> values) {
            addCriterion("register_time in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotIn(List<Date> values) {
            addCriterion("register_time not in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeBetween(Date value1, Date value2) {
            addCriterion("register_time between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotBetween(Date value1, Date value2) {
            addCriterion("register_time not between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andCarNoIsNull() {
            addCriterion("car_no is null");
            return (Criteria) this;
        }

        public Criteria andCarNoIsNotNull() {
            addCriterion("car_no is not null");
            return (Criteria) this;
        }

        public Criteria andCarNoEqualTo(String value) {
            addCriterion("car_no =", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoNotEqualTo(String value) {
            addCriterion("car_no <>", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoGreaterThan(String value) {
            addCriterion("car_no >", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoGreaterThanOrEqualTo(String value) {
            addCriterion("car_no >=", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoLessThan(String value) {
            addCriterion("car_no <", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoLessThanOrEqualTo(String value) {
            addCriterion("car_no <=", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoLike(String value) {
            addCriterion("car_no like", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoNotLike(String value) {
            addCriterion("car_no not like", value, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoIn(List<String> values) {
            addCriterion("car_no in", values, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoNotIn(List<String> values) {
            addCriterion("car_no not in", values, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoBetween(String value1, String value2) {
            addCriterion("car_no between", value1, value2, "carNo");
            return (Criteria) this;
        }

        public Criteria andCarNoNotBetween(String value1, String value2) {
            addCriterion("car_no not between", value1, value2, "carNo");
            return (Criteria) this;
        }

        public Criteria andUnuseDvrCntIsNull() {
            addCriterion("unuse_dvr_cnt is null");
            return (Criteria) this;
        }

        public Criteria andUnuseDvrCntIsNotNull() {
            addCriterion("unuse_dvr_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andUnuseDvrCntEqualTo(Short value) {
            addCriterion("unuse_dvr_cnt =", value, "unuseDvrCnt");
            return (Criteria) this;
        }

        public Criteria andUnuseDvrCntNotEqualTo(Short value) {
            addCriterion("unuse_dvr_cnt <>", value, "unuseDvrCnt");
            return (Criteria) this;
        }

        public Criteria andUnuseDvrCntGreaterThan(Short value) {
            addCriterion("unuse_dvr_cnt >", value, "unuseDvrCnt");
            return (Criteria) this;
        }

        public Criteria andUnuseDvrCntGreaterThanOrEqualTo(Short value) {
            addCriterion("unuse_dvr_cnt >=", value, "unuseDvrCnt");
            return (Criteria) this;
        }

        public Criteria andUnuseDvrCntLessThan(Short value) {
            addCriterion("unuse_dvr_cnt <", value, "unuseDvrCnt");
            return (Criteria) this;
        }

        public Criteria andUnuseDvrCntLessThanOrEqualTo(Short value) {
            addCriterion("unuse_dvr_cnt <=", value, "unuseDvrCnt");
            return (Criteria) this;
        }

        public Criteria andUnuseDvrCntIn(List<Short> values) {
            addCriterion("unuse_dvr_cnt in", values, "unuseDvrCnt");
            return (Criteria) this;
        }

        public Criteria andUnuseDvrCntNotIn(List<Short> values) {
            addCriterion("unuse_dvr_cnt not in", values, "unuseDvrCnt");
            return (Criteria) this;
        }

        public Criteria andUnuseDvrCntBetween(Short value1, Short value2) {
            addCriterion("unuse_dvr_cnt between", value1, value2, "unuseDvrCnt");
            return (Criteria) this;
        }

        public Criteria andUnuseDvrCntNotBetween(Short value1, Short value2) {
            addCriterion("unuse_dvr_cnt not between", value1, value2, "unuseDvrCnt");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andWarmChgPwDtIsNull() {
            addCriterion("warm_chg_pw_dt is null");
            return (Criteria) this;
        }

        public Criteria andWarmChgPwDtIsNotNull() {
            addCriterion("warm_chg_pw_dt is not null");
            return (Criteria) this;
        }

        public Criteria andWarmChgPwDtEqualTo(Date value) {
            addCriterionForJDBCDate("warm_chg_pw_dt =", value, "warmChgPwDt");
            return (Criteria) this;
        }

        public Criteria andWarmChgPwDtNotEqualTo(Date value) {
            addCriterionForJDBCDate("warm_chg_pw_dt <>", value, "warmChgPwDt");
            return (Criteria) this;
        }

        public Criteria andWarmChgPwDtGreaterThan(Date value) {
            addCriterionForJDBCDate("warm_chg_pw_dt >", value, "warmChgPwDt");
            return (Criteria) this;
        }

        public Criteria andWarmChgPwDtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("warm_chg_pw_dt >=", value, "warmChgPwDt");
            return (Criteria) this;
        }

        public Criteria andWarmChgPwDtLessThan(Date value) {
            addCriterionForJDBCDate("warm_chg_pw_dt <", value, "warmChgPwDt");
            return (Criteria) this;
        }

        public Criteria andWarmChgPwDtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("warm_chg_pw_dt <=", value, "warmChgPwDt");
            return (Criteria) this;
        }

        public Criteria andWarmChgPwDtIn(List<Date> values) {
            addCriterionForJDBCDate("warm_chg_pw_dt in", values, "warmChgPwDt");
            return (Criteria) this;
        }

        public Criteria andWarmChgPwDtNotIn(List<Date> values) {
            addCriterionForJDBCDate("warm_chg_pw_dt not in", values, "warmChgPwDt");
            return (Criteria) this;
        }

        public Criteria andWarmChgPwDtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("warm_chg_pw_dt between", value1, value2, "warmChgPwDt");
            return (Criteria) this;
        }

        public Criteria andWarmChgPwDtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("warm_chg_pw_dt not between", value1, value2, "warmChgPwDt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_customer
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_customer
     *
     * @mbg.generated Thu Jun 04 09:20:09 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}