package tw.msigDvrBack.persistence;

import java.io.Serializable;

public class TbCustOpenidKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_openid.user_id
     *
     * @mbggenerated Tue May 31 11:54:18 GMT+08:00 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_openid.OPENID_TYPE
     *
     * @mbggenerated Tue May 31 11:54:18 GMT+08:00 2016
     */
    private String openidType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cust_openid
     *
     * @mbggenerated Tue May 31 11:54:18 GMT+08:00 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_openid.user_id
     *
     * @return the value of tb_cust_openid.user_id
     *
     * @mbggenerated Tue May 31 11:54:18 GMT+08:00 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_openid.user_id
     *
     * @param userId the value for tb_cust_openid.user_id
     *
     * @mbggenerated Tue May 31 11:54:18 GMT+08:00 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_openid.OPENID_TYPE
     *
     * @return the value of tb_cust_openid.OPENID_TYPE
     *
     * @mbggenerated Tue May 31 11:54:18 GMT+08:00 2016
     */
    public String getOpenidType() {
        return openidType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_openid.OPENID_TYPE
     *
     * @param openidType the value for tb_cust_openid.OPENID_TYPE
     *
     * @mbggenerated Tue May 31 11:54:18 GMT+08:00 2016
     */
    public void setOpenidType(String openidType) {
        this.openidType = openidType == null ? null : openidType.trim();
    }
}