package tw.msigDvrBack.persistence;

import java.io.Serializable;
import java.util.Date;

public class TbCustomer implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.user_id
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.user_name
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.eng_name
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String engName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.nickname
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.email
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.mobile_phone
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String mobilePhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.password
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.sex
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.dob
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private Date dob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.contact_phone
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String contactPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.addr
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String addr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cust_status
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String custStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.pic_url
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String picUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cuid
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String cuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.agree_time
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private Date agreeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.acc_ctc_name
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String accCtcName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.acc_ctc_mobile
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String accCtcMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.pwd_status
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String pwdStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.app_login_time
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private Date appLoginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cr_user
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String crUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.cr_date
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private Date crDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.userstamp
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String userstamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.datestamp
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private Date datestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.register_time
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private Date registerTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.car_no
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String carNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.unuse_dvr_cnt
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private Short unuseDvrCnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.remarks
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_customer.warm_chg_pw_dt
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private Date warmChgPwDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_customer
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	private String sn;
	
	private static final long serialVersionUID = 1L;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.user_id
	 * @return  the value of tb_customer.user_id
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.user_id
	 * @param userId  the value for tb_customer.user_id
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.user_name
	 * @return  the value of tb_customer.user_name
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.user_name
	 * @param userName  the value for tb_customer.user_name
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.eng_name
	 * @return  the value of tb_customer.eng_name
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getEngName() {
		return engName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.eng_name
	 * @param engName  the value for tb_customer.eng_name
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setEngName(String engName) {
		this.engName = engName == null ? null : engName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.nickname
	 * @return  the value of tb_customer.nickname
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.nickname
	 * @param nickname  the value for tb_customer.nickname
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname == null ? null : nickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.email
	 * @return  the value of tb_customer.email
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.email
	 * @param email  the value for tb_customer.email
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.mobile_phone
	 * @return  the value of tb_customer.mobile_phone
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getMobilePhone() {
		return mobilePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.mobile_phone
	 * @param mobilePhone  the value for tb_customer.mobile_phone
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.password
	 * @return  the value of tb_customer.password
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.password
	 * @param password  the value for tb_customer.password
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.sex
	 * @return  the value of tb_customer.sex
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.sex
	 * @param sex  the value for tb_customer.sex
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.dob
	 * @return  the value of tb_customer.dob
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public Date getDob() {
		return dob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.dob
	 * @param dob  the value for tb_customer.dob
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setDob(Date dob) {
		this.dob = dob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.contact_phone
	 * @return  the value of tb_customer.contact_phone
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getContactPhone() {
		return contactPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.contact_phone
	 * @param contactPhone  the value for tb_customer.contact_phone
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone == null ? null : contactPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.addr
	 * @return  the value of tb_customer.addr
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getAddr() {
		return addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.addr
	 * @param addr  the value for tb_customer.addr
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setAddr(String addr) {
		this.addr = addr == null ? null : addr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cust_status
	 * @return  the value of tb_customer.cust_status
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getCustStatus() {
		return custStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cust_status
	 * @param custStatus  the value for tb_customer.cust_status
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setCustStatus(String custStatus) {
		this.custStatus = custStatus == null ? null : custStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.pic_url
	 * @return  the value of tb_customer.pic_url
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getPicUrl() {
		return picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.pic_url
	 * @param picUrl  the value for tb_customer.pic_url
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl == null ? null : picUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cuid
	 * @return  the value of tb_customer.cuid
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getCuid() {
		return cuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cuid
	 * @param cuid  the value for tb_customer.cuid
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setCuid(String cuid) {
		this.cuid = cuid == null ? null : cuid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.agree_time
	 * @return  the value of tb_customer.agree_time
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public Date getAgreeTime() {
		return agreeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.agree_time
	 * @param agreeTime  the value for tb_customer.agree_time
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setAgreeTime(Date agreeTime) {
		this.agreeTime = agreeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.acc_ctc_name
	 * @return  the value of tb_customer.acc_ctc_name
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getAccCtcName() {
		return accCtcName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.acc_ctc_name
	 * @param accCtcName  the value for tb_customer.acc_ctc_name
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setAccCtcName(String accCtcName) {
		this.accCtcName = accCtcName == null ? null : accCtcName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.acc_ctc_mobile
	 * @return  the value of tb_customer.acc_ctc_mobile
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getAccCtcMobile() {
		return accCtcMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.acc_ctc_mobile
	 * @param accCtcMobile  the value for tb_customer.acc_ctc_mobile
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setAccCtcMobile(String accCtcMobile) {
		this.accCtcMobile = accCtcMobile == null ? null : accCtcMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.pwd_status
	 * @return  the value of tb_customer.pwd_status
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getPwdStatus() {
		return pwdStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.pwd_status
	 * @param pwdStatus  the value for tb_customer.pwd_status
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setPwdStatus(String pwdStatus) {
		this.pwdStatus = pwdStatus == null ? null : pwdStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.app_login_time
	 * @return  the value of tb_customer.app_login_time
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public Date getAppLoginTime() {
		return appLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.app_login_time
	 * @param appLoginTime  the value for tb_customer.app_login_time
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setAppLoginTime(Date appLoginTime) {
		this.appLoginTime = appLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cr_user
	 * @return  the value of tb_customer.cr_user
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getCrUser() {
		return crUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cr_user
	 * @param crUser  the value for tb_customer.cr_user
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setCrUser(String crUser) {
		this.crUser = crUser == null ? null : crUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.cr_date
	 * @return  the value of tb_customer.cr_date
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public Date getCrDate() {
		return crDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.cr_date
	 * @param crDate  the value for tb_customer.cr_date
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.userstamp
	 * @return  the value of tb_customer.userstamp
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getUserstamp() {
		return userstamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.userstamp
	 * @param userstamp  the value for tb_customer.userstamp
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setUserstamp(String userstamp) {
		this.userstamp = userstamp == null ? null : userstamp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.datestamp
	 * @return  the value of tb_customer.datestamp
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public Date getDatestamp() {
		return datestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.datestamp
	 * @param datestamp  the value for tb_customer.datestamp
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setDatestamp(Date datestamp) {
		this.datestamp = datestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.register_time
	 * @return  the value of tb_customer.register_time
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public Date getRegisterTime() {
		return registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.register_time
	 * @param registerTime  the value for tb_customer.register_time
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.car_no
	 * @return  the value of tb_customer.car_no
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getCarNo() {
		return carNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.car_no
	 * @param carNo  the value for tb_customer.car_no
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setCarNo(String carNo) {
		this.carNo = carNo == null ? null : carNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.unuse_dvr_cnt
	 * @return  the value of tb_customer.unuse_dvr_cnt
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public Short getUnuseDvrCnt() {
		return unuseDvrCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.unuse_dvr_cnt
	 * @param unuseDvrCnt  the value for tb_customer.unuse_dvr_cnt
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setUnuseDvrCnt(Short unuseDvrCnt) {
		this.unuseDvrCnt = unuseDvrCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.remarks
	 * @return  the value of tb_customer.remarks
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.remarks
	 * @param remarks  the value for tb_customer.remarks
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_customer.warm_chg_pw_dt
	 * @return  the value of tb_customer.warm_chg_pw_dt
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public Date getWarmChgPwDt() {
		return warmChgPwDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_customer.warm_chg_pw_dt
	 * @param warmChgPwDt  the value for tb_customer.warm_chg_pw_dt
	 * @mbg.generated  Thu Jun 04 09:20:09 GMT+08:00 2020
	 */
	public void setWarmChgPwDt(Date warmChgPwDt) {
		this.warmChgPwDt = warmChgPwDt;
	}

	public String getSn() {
		return sn;
	}

	public void setSn(String sn) {
		this.sn = sn;
	}
    
}