package tw.msigDvrBack.persistence;

import java.io.Serializable;
import java.util.Date;

public class TbCustCar implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.user_id
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.car_no
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String carNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.eff_mileage
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private Integer effMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.eff_mileage_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private Date effMileageDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.eff_mileage_img
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String effMileageImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.end_mileage
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private Integer endMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.end_mileage_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private Date endMileageDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.end_mileage_img
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String endMileageImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.car_label
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String carLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.car_type
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.car_norm
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String carNorm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.oil_type
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String oilType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.eff_ubi_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private Date effUbiDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.end_ubi_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private Date endUbiDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.ubi_mark
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String ubiMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.vip_type
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String vipType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.mileage_status
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String mileageStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.reset_time
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private Date resetTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.servicer
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String servicer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.prom_code
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String promCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.carno_update
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private Date carnoUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.cr_user
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String crUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.cr_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private Date crDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.userstamp
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private String userstamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cust_car.datestamp
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private Date datestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cust_car
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.user_id
     *
     * @return the value of tb_cust_car.user_id
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.user_id
     *
     * @param userId the value for tb_cust_car.user_id
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.car_no
     *
     * @return the value of tb_cust_car.car_no
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getCarNo() {
        return carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.car_no
     *
     * @param carNo the value for tb_cust_car.car_no
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setCarNo(String carNo) {
        this.carNo = carNo == null ? null : carNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.eff_mileage
     *
     * @return the value of tb_cust_car.eff_mileage
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public Integer getEffMileage() {
        return effMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.eff_mileage
     *
     * @param effMileage the value for tb_cust_car.eff_mileage
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setEffMileage(Integer effMileage) {
        this.effMileage = effMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.eff_mileage_date
     *
     * @return the value of tb_cust_car.eff_mileage_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public Date getEffMileageDate() {
        return effMileageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.eff_mileage_date
     *
     * @param effMileageDate the value for tb_cust_car.eff_mileage_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setEffMileageDate(Date effMileageDate) {
        this.effMileageDate = effMileageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.eff_mileage_img
     *
     * @return the value of tb_cust_car.eff_mileage_img
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getEffMileageImg() {
        return effMileageImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.eff_mileage_img
     *
     * @param effMileageImg the value for tb_cust_car.eff_mileage_img
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setEffMileageImg(String effMileageImg) {
        this.effMileageImg = effMileageImg == null ? null : effMileageImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.end_mileage
     *
     * @return the value of tb_cust_car.end_mileage
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public Integer getEndMileage() {
        return endMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.end_mileage
     *
     * @param endMileage the value for tb_cust_car.end_mileage
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setEndMileage(Integer endMileage) {
        this.endMileage = endMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.end_mileage_date
     *
     * @return the value of tb_cust_car.end_mileage_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public Date getEndMileageDate() {
        return endMileageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.end_mileage_date
     *
     * @param endMileageDate the value for tb_cust_car.end_mileage_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setEndMileageDate(Date endMileageDate) {
        this.endMileageDate = endMileageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.end_mileage_img
     *
     * @return the value of tb_cust_car.end_mileage_img
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getEndMileageImg() {
        return endMileageImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.end_mileage_img
     *
     * @param endMileageImg the value for tb_cust_car.end_mileage_img
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setEndMileageImg(String endMileageImg) {
        this.endMileageImg = endMileageImg == null ? null : endMileageImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.car_label
     *
     * @return the value of tb_cust_car.car_label
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getCarLabel() {
        return carLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.car_label
     *
     * @param carLabel the value for tb_cust_car.car_label
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setCarLabel(String carLabel) {
        this.carLabel = carLabel == null ? null : carLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.car_type
     *
     * @return the value of tb_cust_car.car_type
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.car_type
     *
     * @param carType the value for tb_cust_car.car_type
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.car_norm
     *
     * @return the value of tb_cust_car.car_norm
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getCarNorm() {
        return carNorm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.car_norm
     *
     * @param carNorm the value for tb_cust_car.car_norm
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setCarNorm(String carNorm) {
        this.carNorm = carNorm == null ? null : carNorm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.oil_type
     *
     * @return the value of tb_cust_car.oil_type
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getOilType() {
        return oilType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.oil_type
     *
     * @param oilType the value for tb_cust_car.oil_type
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setOilType(String oilType) {
        this.oilType = oilType == null ? null : oilType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.eff_ubi_date
     *
     * @return the value of tb_cust_car.eff_ubi_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public Date getEffUbiDate() {
        return effUbiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.eff_ubi_date
     *
     * @param effUbiDate the value for tb_cust_car.eff_ubi_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setEffUbiDate(Date effUbiDate) {
        this.effUbiDate = effUbiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.end_ubi_date
     *
     * @return the value of tb_cust_car.end_ubi_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public Date getEndUbiDate() {
        return endUbiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.end_ubi_date
     *
     * @param endUbiDate the value for tb_cust_car.end_ubi_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setEndUbiDate(Date endUbiDate) {
        this.endUbiDate = endUbiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.ubi_mark
     *
     * @return the value of tb_cust_car.ubi_mark
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getUbiMark() {
        return ubiMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.ubi_mark
     *
     * @param ubiMark the value for tb_cust_car.ubi_mark
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setUbiMark(String ubiMark) {
        this.ubiMark = ubiMark == null ? null : ubiMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.vip_type
     *
     * @return the value of tb_cust_car.vip_type
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getVipType() {
        return vipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.vip_type
     *
     * @param vipType the value for tb_cust_car.vip_type
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setVipType(String vipType) {
        this.vipType = vipType == null ? null : vipType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.mileage_status
     *
     * @return the value of tb_cust_car.mileage_status
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getMileageStatus() {
        return mileageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.mileage_status
     *
     * @param mileageStatus the value for tb_cust_car.mileage_status
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setMileageStatus(String mileageStatus) {
        this.mileageStatus = mileageStatus == null ? null : mileageStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.reset_time
     *
     * @return the value of tb_cust_car.reset_time
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public Date getResetTime() {
        return resetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.reset_time
     *
     * @param resetTime the value for tb_cust_car.reset_time
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setResetTime(Date resetTime) {
        this.resetTime = resetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.servicer
     *
     * @return the value of tb_cust_car.servicer
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getServicer() {
        return servicer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.servicer
     *
     * @param servicer the value for tb_cust_car.servicer
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setServicer(String servicer) {
        this.servicer = servicer == null ? null : servicer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.prom_code
     *
     * @return the value of tb_cust_car.prom_code
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getPromCode() {
        return promCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.prom_code
     *
     * @param promCode the value for tb_cust_car.prom_code
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setPromCode(String promCode) {
        this.promCode = promCode == null ? null : promCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.carno_update
     *
     * @return the value of tb_cust_car.carno_update
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public Date getCarnoUpdate() {
        return carnoUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.carno_update
     *
     * @param carnoUpdate the value for tb_cust_car.carno_update
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setCarnoUpdate(Date carnoUpdate) {
        this.carnoUpdate = carnoUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.cr_user
     *
     * @return the value of tb_cust_car.cr_user
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.cr_user
     *
     * @param crUser the value for tb_cust_car.cr_user
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser == null ? null : crUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.cr_date
     *
     * @return the value of tb_cust_car.cr_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.cr_date
     *
     * @param crDate the value for tb_cust_car.cr_date
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.userstamp
     *
     * @return the value of tb_cust_car.userstamp
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public String getUserstamp() {
        return userstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.userstamp
     *
     * @param userstamp the value for tb_cust_car.userstamp
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setUserstamp(String userstamp) {
        this.userstamp = userstamp == null ? null : userstamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cust_car.datestamp
     *
     * @return the value of tb_cust_car.datestamp
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public Date getDatestamp() {
        return datestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cust_car.datestamp
     *
     * @param datestamp the value for tb_cust_car.datestamp
     *
     * @mbg.generated Fri Nov 02 12:05:45 GMT+08:00 2018
     */
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }
}