package tw.msigDvrBack.persistence;

import java.io.Serializable;
import java.util.Date;

public class TbGfbDeviceId implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_device_id.user_id
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_device_id.gfb_device_id
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    private String gfbDeviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_device_id.cr_user
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    private String crUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_device_id.cr_date
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    private Date crDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_device_id.userstamp
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    private String userstamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_device_id.datestamp
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    private Date datestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_device_id.group_status
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    private String groupStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_gfb_device_id
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_device_id.user_id
     *
     * @return the value of tb_gfb_device_id.user_id
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_device_id.user_id
     *
     * @param userId the value for tb_gfb_device_id.user_id
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_device_id.gfb_device_id
     *
     * @return the value of tb_gfb_device_id.gfb_device_id
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    public String getGfbDeviceId() {
        return gfbDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_device_id.gfb_device_id
     *
     * @param gfbDeviceId the value for tb_gfb_device_id.gfb_device_id
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    public void setGfbDeviceId(String gfbDeviceId) {
        this.gfbDeviceId = gfbDeviceId == null ? null : gfbDeviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_device_id.cr_user
     *
     * @return the value of tb_gfb_device_id.cr_user
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_device_id.cr_user
     *
     * @param crUser the value for tb_gfb_device_id.cr_user
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser == null ? null : crUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_device_id.cr_date
     *
     * @return the value of tb_gfb_device_id.cr_date
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_device_id.cr_date
     *
     * @param crDate the value for tb_gfb_device_id.cr_date
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_device_id.userstamp
     *
     * @return the value of tb_gfb_device_id.userstamp
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    public String getUserstamp() {
        return userstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_device_id.userstamp
     *
     * @param userstamp the value for tb_gfb_device_id.userstamp
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    public void setUserstamp(String userstamp) {
        this.userstamp = userstamp == null ? null : userstamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_device_id.datestamp
     *
     * @return the value of tb_gfb_device_id.datestamp
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    public Date getDatestamp() {
        return datestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_device_id.datestamp
     *
     * @param datestamp the value for tb_gfb_device_id.datestamp
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_device_id.group_status
     *
     * @return the value of tb_gfb_device_id.group_status
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    public String getGroupStatus() {
        return groupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_device_id.group_status
     *
     * @param groupStatus the value for tb_gfb_device_id.group_status
     *
     * @mbg.generated Tue Nov 06 16:48:06 GMT+08:00 2018
     */
    public void setGroupStatus(String groupStatus) {
        this.groupStatus = groupStatus == null ? null : groupStatus.trim();
    }
}