package tw.msigDvrBack.persistence;

import java.io.Serializable;
import java.util.Date;

public class TbGfbMsg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.seq_no
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private Integer seqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.msg_type
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private String msgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.msg_class
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private String msgClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.msg_title
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private String msgTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.msg_text
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private String msgText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.news_seq_no
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private Integer newsSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.user_id
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.gfb_device_id
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private String gfbDeviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.pre_push_time
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private Date prePushTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.push_time
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private Date pushTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.push_status
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private String pushStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.comp_date
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private Date compDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.err_email
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private String errEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.err_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private String errMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.cr_user
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private String crUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.cr_date
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private Date crDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.userstamp
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private String userstamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gfb_msg.datestamp
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private Date datestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_gfb_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.seq_no
     *
     * @return the value of tb_gfb_msg.seq_no
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.seq_no
     *
     * @param seqNo the value for tb_gfb_msg.seq_no
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.msg_type
     *
     * @return the value of tb_gfb_msg.msg_type
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.msg_type
     *
     * @param msgType the value for tb_gfb_msg.msg_type
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType == null ? null : msgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.msg_class
     *
     * @return the value of tb_gfb_msg.msg_class
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public String getMsgClass() {
        return msgClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.msg_class
     *
     * @param msgClass the value for tb_gfb_msg.msg_class
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setMsgClass(String msgClass) {
        this.msgClass = msgClass == null ? null : msgClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.msg_title
     *
     * @return the value of tb_gfb_msg.msg_title
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public String getMsgTitle() {
        return msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.msg_title
     *
     * @param msgTitle the value for tb_gfb_msg.msg_title
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setMsgTitle(String msgTitle) {
        this.msgTitle = msgTitle == null ? null : msgTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.msg_text
     *
     * @return the value of tb_gfb_msg.msg_text
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public String getMsgText() {
        return msgText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.msg_text
     *
     * @param msgText the value for tb_gfb_msg.msg_text
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setMsgText(String msgText) {
        this.msgText = msgText == null ? null : msgText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.news_seq_no
     *
     * @return the value of tb_gfb_msg.news_seq_no
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public Integer getNewsSeqNo() {
        return newsSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.news_seq_no
     *
     * @param newsSeqNo the value for tb_gfb_msg.news_seq_no
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setNewsSeqNo(Integer newsSeqNo) {
        this.newsSeqNo = newsSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.user_id
     *
     * @return the value of tb_gfb_msg.user_id
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.user_id
     *
     * @param userId the value for tb_gfb_msg.user_id
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.gfb_device_id
     *
     * @return the value of tb_gfb_msg.gfb_device_id
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public String getGfbDeviceId() {
        return gfbDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.gfb_device_id
     *
     * @param gfbDeviceId the value for tb_gfb_msg.gfb_device_id
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setGfbDeviceId(String gfbDeviceId) {
        this.gfbDeviceId = gfbDeviceId == null ? null : gfbDeviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.pre_push_time
     *
     * @return the value of tb_gfb_msg.pre_push_time
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public Date getPrePushTime() {
        return prePushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.pre_push_time
     *
     * @param prePushTime the value for tb_gfb_msg.pre_push_time
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setPrePushTime(Date prePushTime) {
        this.prePushTime = prePushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.push_time
     *
     * @return the value of tb_gfb_msg.push_time
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public Date getPushTime() {
        return pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.push_time
     *
     * @param pushTime the value for tb_gfb_msg.push_time
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setPushTime(Date pushTime) {
        this.pushTime = pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.push_status
     *
     * @return the value of tb_gfb_msg.push_status
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public String getPushStatus() {
        return pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.push_status
     *
     * @param pushStatus the value for tb_gfb_msg.push_status
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setPushStatus(String pushStatus) {
        this.pushStatus = pushStatus == null ? null : pushStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.comp_date
     *
     * @return the value of tb_gfb_msg.comp_date
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public Date getCompDate() {
        return compDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.comp_date
     *
     * @param compDate the value for tb_gfb_msg.comp_date
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setCompDate(Date compDate) {
        this.compDate = compDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.err_email
     *
     * @return the value of tb_gfb_msg.err_email
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public String getErrEmail() {
        return errEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.err_email
     *
     * @param errEmail the value for tb_gfb_msg.err_email
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setErrEmail(String errEmail) {
        this.errEmail = errEmail == null ? null : errEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.err_msg
     *
     * @return the value of tb_gfb_msg.err_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.err_msg
     *
     * @param errMsg the value for tb_gfb_msg.err_msg
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg == null ? null : errMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.cr_user
     *
     * @return the value of tb_gfb_msg.cr_user
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.cr_user
     *
     * @param crUser the value for tb_gfb_msg.cr_user
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser == null ? null : crUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.cr_date
     *
     * @return the value of tb_gfb_msg.cr_date
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.cr_date
     *
     * @param crDate the value for tb_gfb_msg.cr_date
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.userstamp
     *
     * @return the value of tb_gfb_msg.userstamp
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public String getUserstamp() {
        return userstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.userstamp
     *
     * @param userstamp the value for tb_gfb_msg.userstamp
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setUserstamp(String userstamp) {
        this.userstamp = userstamp == null ? null : userstamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_gfb_msg.datestamp
     *
     * @return the value of tb_gfb_msg.datestamp
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public Date getDatestamp() {
        return datestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_gfb_msg.datestamp
     *
     * @param datestamp the value for tb_gfb_msg.datestamp
     *
     * @mbg.generated Tue Oct 23 18:05:20 GMT+08:00 2018
     */
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }
}