package tw.msigDvrBack.persistence;

import java.io.Serializable;
import java.util.Date;

public class TbLookupCde extends TbLookupCdeKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_cde.dscr
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    private String dscr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_cde.value
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    private Long value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_cde.type1
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    private String type1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_cde.type2
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    private String type2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_cde.type3
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    private String type3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_cde.cr_user
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    private String crUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_cde.cr_date
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    private Date crDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_cde.userstamp
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    private String userstamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_cde.datestamp
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    private Date datestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_lookup_cde
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_cde.dscr
     *
     * @return the value of tb_lookup_cde.dscr
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public String getDscr() {
        return dscr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_cde.dscr
     *
     * @param dscr the value for tb_lookup_cde.dscr
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public void setDscr(String dscr) {
        this.dscr = dscr == null ? null : dscr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_cde.value
     *
     * @return the value of tb_lookup_cde.value
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public Long getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_cde.value
     *
     * @param value the value for tb_lookup_cde.value
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public void setValue(Long value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_cde.type1
     *
     * @return the value of tb_lookup_cde.type1
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public String getType1() {
        return type1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_cde.type1
     *
     * @param type1 the value for tb_lookup_cde.type1
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public void setType1(String type1) {
        this.type1 = type1 == null ? null : type1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_cde.type2
     *
     * @return the value of tb_lookup_cde.type2
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public String getType2() {
        return type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_cde.type2
     *
     * @param type2 the value for tb_lookup_cde.type2
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public void setType2(String type2) {
        this.type2 = type2 == null ? null : type2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_cde.type3
     *
     * @return the value of tb_lookup_cde.type3
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public String getType3() {
        return type3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_cde.type3
     *
     * @param type3 the value for tb_lookup_cde.type3
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public void setType3(String type3) {
        this.type3 = type3 == null ? null : type3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_cde.cr_user
     *
     * @return the value of tb_lookup_cde.cr_user
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_cde.cr_user
     *
     * @param crUser the value for tb_lookup_cde.cr_user
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser == null ? null : crUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_cde.cr_date
     *
     * @return the value of tb_lookup_cde.cr_date
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_cde.cr_date
     *
     * @param crDate the value for tb_lookup_cde.cr_date
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_cde.userstamp
     *
     * @return the value of tb_lookup_cde.userstamp
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public String getUserstamp() {
        return userstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_cde.userstamp
     *
     * @param userstamp the value for tb_lookup_cde.userstamp
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public void setUserstamp(String userstamp) {
        this.userstamp = userstamp == null ? null : userstamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_cde.datestamp
     *
     * @return the value of tb_lookup_cde.datestamp
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public Date getDatestamp() {
        return datestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_cde.datestamp
     *
     * @param datestamp the value for tb_lookup_cde.datestamp
     *
     * @mbg.generated Tue Sep 25 16:42:56 CST 2018
     */
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }
}