package tw.msigDvrBack.persistence;

import java.io.Serializable;
import java.util.Date;

public class TbLookupType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_type.LOOKUP_TYPE
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    private String lookupType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_type.DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    private String dscr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_type.VALUE_DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    private String valueDscr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_type.TYPE1_DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    private String type1Dscr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_type.TYPE2_DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    private String type2Dscr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_type.TYPE3_DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    private String type3Dscr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_type.SYS_INDIC
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    private String sysIndic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_type.CR_USER
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_type.CR_DATE
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    private Date crDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_type.USERSTAMP
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    private String userstamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lookup_type.datestamp
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    private Date datestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_lookup_type
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_type.LOOKUP_TYPE
     *
     * @return the value of tb_lookup_type.LOOKUP_TYPE
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public String getLookupType() {
        return lookupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_type.LOOKUP_TYPE
     *
     * @param lookupType the value for tb_lookup_type.LOOKUP_TYPE
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public void setLookupType(String lookupType) {
        this.lookupType = lookupType == null ? null : lookupType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_type.DSCR
     *
     * @return the value of tb_lookup_type.DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public String getDscr() {
        return dscr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_type.DSCR
     *
     * @param dscr the value for tb_lookup_type.DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public void setDscr(String dscr) {
        this.dscr = dscr == null ? null : dscr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_type.VALUE_DSCR
     *
     * @return the value of tb_lookup_type.VALUE_DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public String getValueDscr() {
        return valueDscr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_type.VALUE_DSCR
     *
     * @param valueDscr the value for tb_lookup_type.VALUE_DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public void setValueDscr(String valueDscr) {
        this.valueDscr = valueDscr == null ? null : valueDscr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_type.TYPE1_DSCR
     *
     * @return the value of tb_lookup_type.TYPE1_DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public String getType1Dscr() {
        return type1Dscr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_type.TYPE1_DSCR
     *
     * @param type1Dscr the value for tb_lookup_type.TYPE1_DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public void setType1Dscr(String type1Dscr) {
        this.type1Dscr = type1Dscr == null ? null : type1Dscr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_type.TYPE2_DSCR
     *
     * @return the value of tb_lookup_type.TYPE2_DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public String getType2Dscr() {
        return type2Dscr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_type.TYPE2_DSCR
     *
     * @param type2Dscr the value for tb_lookup_type.TYPE2_DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public void setType2Dscr(String type2Dscr) {
        this.type2Dscr = type2Dscr == null ? null : type2Dscr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_type.TYPE3_DSCR
     *
     * @return the value of tb_lookup_type.TYPE3_DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public String getType3Dscr() {
        return type3Dscr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_type.TYPE3_DSCR
     *
     * @param type3Dscr the value for tb_lookup_type.TYPE3_DSCR
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public void setType3Dscr(String type3Dscr) {
        this.type3Dscr = type3Dscr == null ? null : type3Dscr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_type.SYS_INDIC
     *
     * @return the value of tb_lookup_type.SYS_INDIC
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public String getSysIndic() {
        return sysIndic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_type.SYS_INDIC
     *
     * @param sysIndic the value for tb_lookup_type.SYS_INDIC
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public void setSysIndic(String sysIndic) {
        this.sysIndic = sysIndic == null ? null : sysIndic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_type.CR_USER
     *
     * @return the value of tb_lookup_type.CR_USER
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_type.CR_USER
     *
     * @param crUser the value for tb_lookup_type.CR_USER
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser == null ? null : crUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_type.CR_DATE
     *
     * @return the value of tb_lookup_type.CR_DATE
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_type.CR_DATE
     *
     * @param crDate the value for tb_lookup_type.CR_DATE
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_type.USERSTAMP
     *
     * @return the value of tb_lookup_type.USERSTAMP
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public String getUserstamp() {
        return userstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_type.USERSTAMP
     *
     * @param userstamp the value for tb_lookup_type.USERSTAMP
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public void setUserstamp(String userstamp) {
        this.userstamp = userstamp == null ? null : userstamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lookup_type.datestamp
     *
     * @return the value of tb_lookup_type.datestamp
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public Date getDatestamp() {
        return datestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lookup_type.datestamp
     *
     * @param datestamp the value for tb_lookup_type.datestamp
     *
     * @mbggenerated Tue Aug 25 09:19:27 CST 2015
     */
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }
}