package tw.msigDvrBack.persistence;

import java.io.Serializable;
import java.util.Date;

public class TbNews implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.seq_no
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private Integer seqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.msg_class
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private String msgClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.title
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.content
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.link_url
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.cs_phone
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private String csPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.eff_date
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private Date effDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.end_date
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.pre_push_time
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private Date prePushTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.push_time
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private Date pushTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.push_status
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private String pushStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.cr_user
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private String crUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.cr_date
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private Date crDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.userstamp
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private String userstamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.datestamp
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private Date datestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_news
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.seq_no
     *
     * @return the value of tb_news.seq_no
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.seq_no
     *
     * @param seqNo the value for tb_news.seq_no
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.msg_class
     *
     * @return the value of tb_news.msg_class
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public String getMsgClass() {
        return msgClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.msg_class
     *
     * @param msgClass the value for tb_news.msg_class
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setMsgClass(String msgClass) {
        this.msgClass = msgClass == null ? null : msgClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.title
     *
     * @return the value of tb_news.title
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.title
     *
     * @param title the value for tb_news.title
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.content
     *
     * @return the value of tb_news.content
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.content
     *
     * @param content the value for tb_news.content
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.link_url
     *
     * @return the value of tb_news.link_url
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.link_url
     *
     * @param linkUrl the value for tb_news.link_url
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.cs_phone
     *
     * @return the value of tb_news.cs_phone
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public String getCsPhone() {
        return csPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.cs_phone
     *
     * @param csPhone the value for tb_news.cs_phone
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setCsPhone(String csPhone) {
        this.csPhone = csPhone == null ? null : csPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.eff_date
     *
     * @return the value of tb_news.eff_date
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.eff_date
     *
     * @param effDate the value for tb_news.eff_date
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.end_date
     *
     * @return the value of tb_news.end_date
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.end_date
     *
     * @param endDate the value for tb_news.end_date
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.pre_push_time
     *
     * @return the value of tb_news.pre_push_time
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public Date getPrePushTime() {
        return prePushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.pre_push_time
     *
     * @param prePushTime the value for tb_news.pre_push_time
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setPrePushTime(Date prePushTime) {
        this.prePushTime = prePushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.push_time
     *
     * @return the value of tb_news.push_time
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public Date getPushTime() {
        return pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.push_time
     *
     * @param pushTime the value for tb_news.push_time
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setPushTime(Date pushTime) {
        this.pushTime = pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.push_status
     *
     * @return the value of tb_news.push_status
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public String getPushStatus() {
        return pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.push_status
     *
     * @param pushStatus the value for tb_news.push_status
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setPushStatus(String pushStatus) {
        this.pushStatus = pushStatus == null ? null : pushStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.cr_user
     *
     * @return the value of tb_news.cr_user
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.cr_user
     *
     * @param crUser the value for tb_news.cr_user
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser == null ? null : crUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.cr_date
     *
     * @return the value of tb_news.cr_date
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.cr_date
     *
     * @param crDate the value for tb_news.cr_date
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.userstamp
     *
     * @return the value of tb_news.userstamp
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public String getUserstamp() {
        return userstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.userstamp
     *
     * @param userstamp the value for tb_news.userstamp
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setUserstamp(String userstamp) {
        this.userstamp = userstamp == null ? null : userstamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.datestamp
     *
     * @return the value of tb_news.datestamp
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public Date getDatestamp() {
        return datestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.datestamp
     *
     * @param datestamp the value for tb_news.datestamp
     *
     * @mbg.generated Wed Oct 31 12:04:29 GMT+08:00 2018
     */
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }
}