package tw.msigDvrBack.persistence;

import java.io.Serializable;
import java.util.Date;

public class TbSysPg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_pg.pg_id
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    private String pgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_pg.PG_NAME
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    private String pgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_pg.URL
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_pg.SEQ_NO
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    private Integer seqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_pg.pg_proj_id
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    private String pgProjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_pg.EFF_DATE
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    private Date effDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_pg.END_DATE
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_pg.cr_user
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_pg.cr_date
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    private Date crDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_pg.userstamp
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    private String userstamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_pg.datestamp
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    private Date datestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_sys_pg
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_pg.pg_id
     *
     * @return the value of tb_sys_pg.pg_id
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public String getPgId() {
        return pgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_pg.pg_id
     *
     * @param pgId the value for tb_sys_pg.pg_id
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public void setPgId(String pgId) {
        this.pgId = pgId == null ? null : pgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_pg.PG_NAME
     *
     * @return the value of tb_sys_pg.PG_NAME
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public String getPgName() {
        return pgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_pg.PG_NAME
     *
     * @param pgName the value for tb_sys_pg.PG_NAME
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public void setPgName(String pgName) {
        this.pgName = pgName == null ? null : pgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_pg.URL
     *
     * @return the value of tb_sys_pg.URL
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_pg.URL
     *
     * @param url the value for tb_sys_pg.URL
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_pg.SEQ_NO
     *
     * @return the value of tb_sys_pg.SEQ_NO
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_pg.SEQ_NO
     *
     * @param seqNo the value for tb_sys_pg.SEQ_NO
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_pg.pg_proj_id
     *
     * @return the value of tb_sys_pg.pg_proj_id
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public String getPgProjId() {
        return pgProjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_pg.pg_proj_id
     *
     * @param pgProjId the value for tb_sys_pg.pg_proj_id
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public void setPgProjId(String pgProjId) {
        this.pgProjId = pgProjId == null ? null : pgProjId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_pg.EFF_DATE
     *
     * @return the value of tb_sys_pg.EFF_DATE
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_pg.EFF_DATE
     *
     * @param effDate the value for tb_sys_pg.EFF_DATE
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_pg.END_DATE
     *
     * @return the value of tb_sys_pg.END_DATE
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_pg.END_DATE
     *
     * @param endDate the value for tb_sys_pg.END_DATE
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_pg.cr_user
     *
     * @return the value of tb_sys_pg.cr_user
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_pg.cr_user
     *
     * @param crUser the value for tb_sys_pg.cr_user
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser == null ? null : crUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_pg.cr_date
     *
     * @return the value of tb_sys_pg.cr_date
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_pg.cr_date
     *
     * @param crDate the value for tb_sys_pg.cr_date
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_pg.userstamp
     *
     * @return the value of tb_sys_pg.userstamp
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public String getUserstamp() {
        return userstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_pg.userstamp
     *
     * @param userstamp the value for tb_sys_pg.userstamp
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public void setUserstamp(String userstamp) {
        this.userstamp = userstamp == null ? null : userstamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_pg.datestamp
     *
     * @return the value of tb_sys_pg.datestamp
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public Date getDatestamp() {
        return datestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_pg.datestamp
     *
     * @param datestamp the value for tb_sys_pg.datestamp
     *
     * @mbggenerated Mon Aug 24 14:19:12 CST 2015
     */
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }
}