package tw.msigDvrBack.persistence;

import java.io.Serializable;
import java.util.Date;

public class TbSysUser implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_user.sys_user_id
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	private String sysUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_user.user_name
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_user.dept_no
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	private String deptNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_user.email
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_user.status
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_user.password
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_user.login_fail_cnt
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	private Short loginFailCnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_user.cr_user
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	private String crUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_user.cr_date
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	private Date crDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_user.userstamp
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	private String userstamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_user.datestamp
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	private Date datestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_sys_user
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_user.sys_user_id
	 * @return  the value of tb_sys_user.sys_user_id
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public String getSysUserId() {
		return sysUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_user.sys_user_id
	 * @param sysUserId  the value for tb_sys_user.sys_user_id
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public void setSysUserId(String sysUserId) {
		this.sysUserId = sysUserId == null ? null : sysUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_user.user_name
	 * @return  the value of tb_sys_user.user_name
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_user.user_name
	 * @param userName  the value for tb_sys_user.user_name
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_user.dept_no
	 * @return  the value of tb_sys_user.dept_no
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public String getDeptNo() {
		return deptNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_user.dept_no
	 * @param deptNo  the value for tb_sys_user.dept_no
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public void setDeptNo(String deptNo) {
		this.deptNo = deptNo == null ? null : deptNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_user.email
	 * @return  the value of tb_sys_user.email
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_user.email
	 * @param email  the value for tb_sys_user.email
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_user.status
	 * @return  the value of tb_sys_user.status
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_user.status
	 * @param status  the value for tb_sys_user.status
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_user.password
	 * @return  the value of tb_sys_user.password
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_user.password
	 * @param pwd  the value for tb_sys_user.password
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd == null ? null : pwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_user.login_fail_cnt
	 * @return  the value of tb_sys_user.login_fail_cnt
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public Short getLoginFailCnt() {
		return loginFailCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_user.login_fail_cnt
	 * @param loginFailCnt  the value for tb_sys_user.login_fail_cnt
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public void setLoginFailCnt(Short loginFailCnt) {
		this.loginFailCnt = loginFailCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_user.cr_user
	 * @return  the value of tb_sys_user.cr_user
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public String getCrUser() {
		return crUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_user.cr_user
	 * @param crUser  the value for tb_sys_user.cr_user
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public void setCrUser(String crUser) {
		this.crUser = crUser == null ? null : crUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_user.cr_date
	 * @return  the value of tb_sys_user.cr_date
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public Date getCrDate() {
		return crDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_user.cr_date
	 * @param crDate  the value for tb_sys_user.cr_date
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_user.userstamp
	 * @return  the value of tb_sys_user.userstamp
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public String getUserstamp() {
		return userstamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_user.userstamp
	 * @param userstamp  the value for tb_sys_user.userstamp
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public void setUserstamp(String userstamp) {
		this.userstamp = userstamp == null ? null : userstamp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_user.datestamp
	 * @return  the value of tb_sys_user.datestamp
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public Date getDatestamp() {
		return datestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_user.datestamp
	 * @param datestamp  the value for tb_sys_user.datestamp
	 * @mbg.generated  Tue Jun 02 09:06:53 GMT+08:00 2020
	 */
	public void setDatestamp(Date datestamp) {
		this.datestamp = datestamp;
	}
}