package tw.msigDvrBack.persistence;

import java.io.Serializable;
import java.util.Date;

public class TbTprodService implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tprod_service.SEQ_NO
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    private Long seqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tprod_service.TPROD_ID
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    private String tprodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tprod_service.SYS_ID
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    private String sysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tprod_service.BILLING_SYS
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    private String billingSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tprod_service.SP_CODE
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    private String spCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tprod_service.SERVICE_ID
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    private String serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tprod_service.MON_AMT
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    private Integer monAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tprod_service.URL
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tprod_service.SELL_INDIC
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    private String sellIndic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tprod_service.CR_USER
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    private String crUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tprod_service.CR_DATE
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    private Date crDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tprod_service.USERSTAMP
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    private String userstamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tprod_service.datestamp
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    private Date datestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_tprod_service
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tprod_service.SEQ_NO
     *
     * @return the value of tb_tprod_service.SEQ_NO
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public Long getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tprod_service.SEQ_NO
     *
     * @param seqNo the value for tb_tprod_service.SEQ_NO
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public void setSeqNo(Long seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tprod_service.TPROD_ID
     *
     * @return the value of tb_tprod_service.TPROD_ID
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public String getTprodId() {
        return tprodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tprod_service.TPROD_ID
     *
     * @param tprodId the value for tb_tprod_service.TPROD_ID
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public void setTprodId(String tprodId) {
        this.tprodId = tprodId == null ? null : tprodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tprod_service.SYS_ID
     *
     * @return the value of tb_tprod_service.SYS_ID
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tprod_service.SYS_ID
     *
     * @param sysId the value for tb_tprod_service.SYS_ID
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public void setSysId(String sysId) {
        this.sysId = sysId == null ? null : sysId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tprod_service.BILLING_SYS
     *
     * @return the value of tb_tprod_service.BILLING_SYS
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public String getBillingSys() {
        return billingSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tprod_service.BILLING_SYS
     *
     * @param billingSys the value for tb_tprod_service.BILLING_SYS
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public void setBillingSys(String billingSys) {
        this.billingSys = billingSys == null ? null : billingSys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tprod_service.SP_CODE
     *
     * @return the value of tb_tprod_service.SP_CODE
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public String getSpCode() {
        return spCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tprod_service.SP_CODE
     *
     * @param spCode the value for tb_tprod_service.SP_CODE
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public void setSpCode(String spCode) {
        this.spCode = spCode == null ? null : spCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tprod_service.SERVICE_ID
     *
     * @return the value of tb_tprod_service.SERVICE_ID
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tprod_service.SERVICE_ID
     *
     * @param serviceId the value for tb_tprod_service.SERVICE_ID
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId == null ? null : serviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tprod_service.MON_AMT
     *
     * @return the value of tb_tprod_service.MON_AMT
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public Integer getMonAmt() {
        return monAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tprod_service.MON_AMT
     *
     * @param monAmt the value for tb_tprod_service.MON_AMT
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public void setMonAmt(Integer monAmt) {
        this.monAmt = monAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tprod_service.URL
     *
     * @return the value of tb_tprod_service.URL
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tprod_service.URL
     *
     * @param url the value for tb_tprod_service.URL
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tprod_service.SELL_INDIC
     *
     * @return the value of tb_tprod_service.SELL_INDIC
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public String getSellIndic() {
        return sellIndic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tprod_service.SELL_INDIC
     *
     * @param sellIndic the value for tb_tprod_service.SELL_INDIC
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public void setSellIndic(String sellIndic) {
        this.sellIndic = sellIndic == null ? null : sellIndic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tprod_service.CR_USER
     *
     * @return the value of tb_tprod_service.CR_USER
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tprod_service.CR_USER
     *
     * @param crUser the value for tb_tprod_service.CR_USER
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser == null ? null : crUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tprod_service.CR_DATE
     *
     * @return the value of tb_tprod_service.CR_DATE
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tprod_service.CR_DATE
     *
     * @param crDate the value for tb_tprod_service.CR_DATE
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tprod_service.USERSTAMP
     *
     * @return the value of tb_tprod_service.USERSTAMP
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public String getUserstamp() {
        return userstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tprod_service.USERSTAMP
     *
     * @param userstamp the value for tb_tprod_service.USERSTAMP
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public void setUserstamp(String userstamp) {
        this.userstamp = userstamp == null ? null : userstamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tprod_service.datestamp
     *
     * @return the value of tb_tprod_service.datestamp
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public Date getDatestamp() {
        return datestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tprod_service.datestamp
     *
     * @param datestamp the value for tb_tprod_service.datestamp
     *
     * @mbggenerated Wed Apr 06 14:46:43 GMT+08:00 2016
     */
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }
}