package tw.msigDvrBack.persistence;

import java.io.Serializable;
import java.util.Date;

public class VwCustUbiApply implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.apply_no
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String applyNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.user_id
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.apply_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private Date applyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.apply_status
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String applyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.insurance_rate
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private Integer insuranceRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.annual_mileage
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private Integer annualMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.car_no
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String carNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.eff_mileage
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private Integer effMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.eff_mileage_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private Date effMileageDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.eff_mileage_img
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String effMileageImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.end_mileage
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private Integer endMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.end_mileage_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private Date endMileageDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.end_mileage_img
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String endMileageImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.chk_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private Date chkDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.comp_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private Date compDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.fail_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private Date failDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.eff_ubi_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private Date effUbiDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.end_ubi_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private Date endUbiDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.ubi_mark
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String ubiMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.contact_phone
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.city
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.area
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.zip
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.cr_user
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String crUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.cr_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private Date crDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.userstamp
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String userstamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.datestamp
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private Date datestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.prom_code
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String promCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.dscr
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String dscr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_cust_ubi_apply.servicer
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private String servicer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vw_cust_ubi_apply
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.apply_no
     *
     * @return the value of vw_cust_ubi_apply.apply_no
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.apply_no
     *
     * @param applyNo the value for vw_cust_ubi_apply.apply_no
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo == null ? null : applyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.user_id
     *
     * @return the value of vw_cust_ubi_apply.user_id
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.user_id
     *
     * @param userId the value for vw_cust_ubi_apply.user_id
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.apply_date
     *
     * @return the value of vw_cust_ubi_apply.apply_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.apply_date
     *
     * @param applyDate the value for vw_cust_ubi_apply.apply_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.apply_status
     *
     * @return the value of vw_cust_ubi_apply.apply_status
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getApplyStatus() {
        return applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.apply_status
     *
     * @param applyStatus the value for vw_cust_ubi_apply.apply_status
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setApplyStatus(String applyStatus) {
        this.applyStatus = applyStatus == null ? null : applyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.insurance_rate
     *
     * @return the value of vw_cust_ubi_apply.insurance_rate
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public Integer getInsuranceRate() {
        return insuranceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.insurance_rate
     *
     * @param insuranceRate the value for vw_cust_ubi_apply.insurance_rate
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setInsuranceRate(Integer insuranceRate) {
        this.insuranceRate = insuranceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.annual_mileage
     *
     * @return the value of vw_cust_ubi_apply.annual_mileage
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public Integer getAnnualMileage() {
        return annualMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.annual_mileage
     *
     * @param annualMileage the value for vw_cust_ubi_apply.annual_mileage
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setAnnualMileage(Integer annualMileage) {
        this.annualMileage = annualMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.car_no
     *
     * @return the value of vw_cust_ubi_apply.car_no
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getCarNo() {
        return carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.car_no
     *
     * @param carNo the value for vw_cust_ubi_apply.car_no
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setCarNo(String carNo) {
        this.carNo = carNo == null ? null : carNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.eff_mileage
     *
     * @return the value of vw_cust_ubi_apply.eff_mileage
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public Integer getEffMileage() {
        return effMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.eff_mileage
     *
     * @param effMileage the value for vw_cust_ubi_apply.eff_mileage
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setEffMileage(Integer effMileage) {
        this.effMileage = effMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.eff_mileage_date
     *
     * @return the value of vw_cust_ubi_apply.eff_mileage_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public Date getEffMileageDate() {
        return effMileageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.eff_mileage_date
     *
     * @param effMileageDate the value for vw_cust_ubi_apply.eff_mileage_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setEffMileageDate(Date effMileageDate) {
        this.effMileageDate = effMileageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.eff_mileage_img
     *
     * @return the value of vw_cust_ubi_apply.eff_mileage_img
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getEffMileageImg() {
        return effMileageImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.eff_mileage_img
     *
     * @param effMileageImg the value for vw_cust_ubi_apply.eff_mileage_img
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setEffMileageImg(String effMileageImg) {
        this.effMileageImg = effMileageImg == null ? null : effMileageImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.end_mileage
     *
     * @return the value of vw_cust_ubi_apply.end_mileage
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public Integer getEndMileage() {
        return endMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.end_mileage
     *
     * @param endMileage the value for vw_cust_ubi_apply.end_mileage
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setEndMileage(Integer endMileage) {
        this.endMileage = endMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.end_mileage_date
     *
     * @return the value of vw_cust_ubi_apply.end_mileage_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public Date getEndMileageDate() {
        return endMileageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.end_mileage_date
     *
     * @param endMileageDate the value for vw_cust_ubi_apply.end_mileage_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setEndMileageDate(Date endMileageDate) {
        this.endMileageDate = endMileageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.end_mileage_img
     *
     * @return the value of vw_cust_ubi_apply.end_mileage_img
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getEndMileageImg() {
        return endMileageImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.end_mileage_img
     *
     * @param endMileageImg the value for vw_cust_ubi_apply.end_mileage_img
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setEndMileageImg(String endMileageImg) {
        this.endMileageImg = endMileageImg == null ? null : endMileageImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.chk_date
     *
     * @return the value of vw_cust_ubi_apply.chk_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public Date getChkDate() {
        return chkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.chk_date
     *
     * @param chkDate the value for vw_cust_ubi_apply.chk_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setChkDate(Date chkDate) {
        this.chkDate = chkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.comp_date
     *
     * @return the value of vw_cust_ubi_apply.comp_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public Date getCompDate() {
        return compDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.comp_date
     *
     * @param compDate the value for vw_cust_ubi_apply.comp_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setCompDate(Date compDate) {
        this.compDate = compDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.fail_date
     *
     * @return the value of vw_cust_ubi_apply.fail_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public Date getFailDate() {
        return failDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.fail_date
     *
     * @param failDate the value for vw_cust_ubi_apply.fail_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setFailDate(Date failDate) {
        this.failDate = failDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.eff_ubi_date
     *
     * @return the value of vw_cust_ubi_apply.eff_ubi_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public Date getEffUbiDate() {
        return effUbiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.eff_ubi_date
     *
     * @param effUbiDate the value for vw_cust_ubi_apply.eff_ubi_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setEffUbiDate(Date effUbiDate) {
        this.effUbiDate = effUbiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.end_ubi_date
     *
     * @return the value of vw_cust_ubi_apply.end_ubi_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public Date getEndUbiDate() {
        return endUbiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.end_ubi_date
     *
     * @param endUbiDate the value for vw_cust_ubi_apply.end_ubi_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setEndUbiDate(Date endUbiDate) {
        this.endUbiDate = endUbiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.ubi_mark
     *
     * @return the value of vw_cust_ubi_apply.ubi_mark
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getUbiMark() {
        return ubiMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.ubi_mark
     *
     * @param ubiMark the value for vw_cust_ubi_apply.ubi_mark
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setUbiMark(String ubiMark) {
        this.ubiMark = ubiMark == null ? null : ubiMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.contact_phone
     *
     * @return the value of vw_cust_ubi_apply.contact_phone
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.contact_phone
     *
     * @param contactPhone the value for vw_cust_ubi_apply.contact_phone
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.city
     *
     * @return the value of vw_cust_ubi_apply.city
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.city
     *
     * @param city the value for vw_cust_ubi_apply.city
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.area
     *
     * @return the value of vw_cust_ubi_apply.area
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.area
     *
     * @param area the value for vw_cust_ubi_apply.area
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.zip
     *
     * @return the value of vw_cust_ubi_apply.zip
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.zip
     *
     * @param zip the value for vw_cust_ubi_apply.zip
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.cr_user
     *
     * @return the value of vw_cust_ubi_apply.cr_user
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.cr_user
     *
     * @param crUser the value for vw_cust_ubi_apply.cr_user
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser == null ? null : crUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.cr_date
     *
     * @return the value of vw_cust_ubi_apply.cr_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.cr_date
     *
     * @param crDate the value for vw_cust_ubi_apply.cr_date
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.userstamp
     *
     * @return the value of vw_cust_ubi_apply.userstamp
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getUserstamp() {
        return userstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.userstamp
     *
     * @param userstamp the value for vw_cust_ubi_apply.userstamp
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setUserstamp(String userstamp) {
        this.userstamp = userstamp == null ? null : userstamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.datestamp
     *
     * @return the value of vw_cust_ubi_apply.datestamp
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public Date getDatestamp() {
        return datestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.datestamp
     *
     * @param datestamp the value for vw_cust_ubi_apply.datestamp
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.prom_code
     *
     * @return the value of vw_cust_ubi_apply.prom_code
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getPromCode() {
        return promCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.prom_code
     *
     * @param promCode the value for vw_cust_ubi_apply.prom_code
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setPromCode(String promCode) {
        this.promCode = promCode == null ? null : promCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.dscr
     *
     * @return the value of vw_cust_ubi_apply.dscr
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getDscr() {
        return dscr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.dscr
     *
     * @param dscr the value for vw_cust_ubi_apply.dscr
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setDscr(String dscr) {
        this.dscr = dscr == null ? null : dscr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_cust_ubi_apply.servicer
     *
     * @return the value of vw_cust_ubi_apply.servicer
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public String getServicer() {
        return servicer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_cust_ubi_apply.servicer
     *
     * @param servicer the value for vw_cust_ubi_apply.servicer
     *
     * @mbg.generated Mon Nov 26 16:38:25 GMT+08:00 2018
     */
    public void setServicer(String servicer) {
        this.servicer = servicer == null ? null : servicer.trim();
    }
}