package tw.msigDvrBack.persistence;

import java.io.Serializable;
import java.util.Date;

public class VwNews implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.seq_no
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private Integer seqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.msg_class
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private String msgClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.title
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.content
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.link_url
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.eff_date
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private Date effDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.end_date
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.pre_push_time
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private Date prePushTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.push_time
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private Date pushTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.push_status
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private String pushStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.cr_user
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private String crUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.cr_date
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private Date crDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.userstamp
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private String userstamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.datestamp
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private Date datestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.email
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.user_id
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.news_user_status
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private String newsUserStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.news_user_push_time
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private Date newsUserPushTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.news_user_seq
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private Integer newsUserSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_news.gfb_device_id
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private String gfbDeviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vw_news
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.seq_no
     *
     * @return the value of vw_news.seq_no
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.seq_no
     *
     * @param seqNo the value for vw_news.seq_no
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.msg_class
     *
     * @return the value of vw_news.msg_class
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public String getMsgClass() {
        return msgClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.msg_class
     *
     * @param msgClass the value for vw_news.msg_class
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setMsgClass(String msgClass) {
        this.msgClass = msgClass == null ? null : msgClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.title
     *
     * @return the value of vw_news.title
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.title
     *
     * @param title the value for vw_news.title
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.content
     *
     * @return the value of vw_news.content
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.content
     *
     * @param content the value for vw_news.content
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.link_url
     *
     * @return the value of vw_news.link_url
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.link_url
     *
     * @param linkUrl the value for vw_news.link_url
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.eff_date
     *
     * @return the value of vw_news.eff_date
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.eff_date
     *
     * @param effDate the value for vw_news.eff_date
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.end_date
     *
     * @return the value of vw_news.end_date
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.end_date
     *
     * @param endDate the value for vw_news.end_date
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.pre_push_time
     *
     * @return the value of vw_news.pre_push_time
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public Date getPrePushTime() {
        return prePushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.pre_push_time
     *
     * @param prePushTime the value for vw_news.pre_push_time
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setPrePushTime(Date prePushTime) {
        this.prePushTime = prePushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.push_time
     *
     * @return the value of vw_news.push_time
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public Date getPushTime() {
        return pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.push_time
     *
     * @param pushTime the value for vw_news.push_time
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setPushTime(Date pushTime) {
        this.pushTime = pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.push_status
     *
     * @return the value of vw_news.push_status
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public String getPushStatus() {
        return pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.push_status
     *
     * @param pushStatus the value for vw_news.push_status
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setPushStatus(String pushStatus) {
        this.pushStatus = pushStatus == null ? null : pushStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.cr_user
     *
     * @return the value of vw_news.cr_user
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.cr_user
     *
     * @param crUser the value for vw_news.cr_user
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser == null ? null : crUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.cr_date
     *
     * @return the value of vw_news.cr_date
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.cr_date
     *
     * @param crDate the value for vw_news.cr_date
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.userstamp
     *
     * @return the value of vw_news.userstamp
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public String getUserstamp() {
        return userstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.userstamp
     *
     * @param userstamp the value for vw_news.userstamp
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setUserstamp(String userstamp) {
        this.userstamp = userstamp == null ? null : userstamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.datestamp
     *
     * @return the value of vw_news.datestamp
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public Date getDatestamp() {
        return datestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.datestamp
     *
     * @param datestamp the value for vw_news.datestamp
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.email
     *
     * @return the value of vw_news.email
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.email
     *
     * @param email the value for vw_news.email
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.user_id
     *
     * @return the value of vw_news.user_id
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.user_id
     *
     * @param userId the value for vw_news.user_id
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.news_user_status
     *
     * @return the value of vw_news.news_user_status
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public String getNewsUserStatus() {
        return newsUserStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.news_user_status
     *
     * @param newsUserStatus the value for vw_news.news_user_status
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setNewsUserStatus(String newsUserStatus) {
        this.newsUserStatus = newsUserStatus == null ? null : newsUserStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.news_user_push_time
     *
     * @return the value of vw_news.news_user_push_time
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public Date getNewsUserPushTime() {
        return newsUserPushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.news_user_push_time
     *
     * @param newsUserPushTime the value for vw_news.news_user_push_time
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setNewsUserPushTime(Date newsUserPushTime) {
        this.newsUserPushTime = newsUserPushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.news_user_seq
     *
     * @return the value of vw_news.news_user_seq
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public Integer getNewsUserSeq() {
        return newsUserSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.news_user_seq
     *
     * @param newsUserSeq the value for vw_news.news_user_seq
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setNewsUserSeq(Integer newsUserSeq) {
        this.newsUserSeq = newsUserSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_news.gfb_device_id
     *
     * @return the value of vw_news.gfb_device_id
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public String getGfbDeviceId() {
        return gfbDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_news.gfb_device_id
     *
     * @param gfbDeviceId the value for vw_news.gfb_device_id
     *
     * @mbg.generated Wed Oct 24 11:10:26 GMT+08:00 2018
     */
    public void setGfbDeviceId(String gfbDeviceId) {
        this.gfbDeviceId = gfbDeviceId == null ? null : gfbDeviceId.trim();
    }
}