package tw.msigDvrBack.persistence;

import java.io.Serializable;
import java.util.Date;

public class VwSysUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_sys_user.sys_user_id
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    private String sysUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_sys_user.user_name
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_sys_user.dept_no
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    private String deptNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_sys_user.dept_dscr
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    private String deptDscr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_sys_user.email
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_sys_user.status
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_sys_user.status_dscr
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    private String statusDscr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_sys_user.password
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_sys_user.login_fail_cnt
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    private Short loginFailCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_sys_user.cr_user
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    private String crUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_sys_user.cr_date
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    private Date crDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_sys_user.userstamp
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    private String userstamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_sys_user.datestamp
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    private Date datestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vw_sys_user
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_sys_user.sys_user_id
     *
     * @return the value of vw_sys_user.sys_user_id
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public String getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_sys_user.sys_user_id
     *
     * @param sysUserId the value for vw_sys_user.sys_user_id
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public void setSysUserId(String sysUserId) {
        this.sysUserId = sysUserId == null ? null : sysUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_sys_user.user_name
     *
     * @return the value of vw_sys_user.user_name
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_sys_user.user_name
     *
     * @param userName the value for vw_sys_user.user_name
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_sys_user.dept_no
     *
     * @return the value of vw_sys_user.dept_no
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public String getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_sys_user.dept_no
     *
     * @param deptNo the value for vw_sys_user.dept_no
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo == null ? null : deptNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_sys_user.dept_dscr
     *
     * @return the value of vw_sys_user.dept_dscr
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public String getDeptDscr() {
        return deptDscr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_sys_user.dept_dscr
     *
     * @param deptDscr the value for vw_sys_user.dept_dscr
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public void setDeptDscr(String deptDscr) {
        this.deptDscr = deptDscr == null ? null : deptDscr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_sys_user.email
     *
     * @return the value of vw_sys_user.email
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_sys_user.email
     *
     * @param email the value for vw_sys_user.email
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_sys_user.status
     *
     * @return the value of vw_sys_user.status
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_sys_user.status
     *
     * @param status the value for vw_sys_user.status
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_sys_user.status_dscr
     *
     * @return the value of vw_sys_user.status_dscr
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public String getStatusDscr() {
        return statusDscr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_sys_user.status_dscr
     *
     * @param statusDscr the value for vw_sys_user.status_dscr
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public void setStatusDscr(String statusDscr) {
        this.statusDscr = statusDscr == null ? null : statusDscr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_sys_user.password
     *
     * @return the value of vw_sys_user.password
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_sys_user.password
     *
     * @param password the value for vw_sys_user.password
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_sys_user.login_fail_cnt
     *
     * @return the value of vw_sys_user.login_fail_cnt
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public Short getLoginFailCnt() {
        return loginFailCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_sys_user.login_fail_cnt
     *
     * @param loginFailCnt the value for vw_sys_user.login_fail_cnt
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public void setLoginFailCnt(Short loginFailCnt) {
        this.loginFailCnt = loginFailCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_sys_user.cr_user
     *
     * @return the value of vw_sys_user.cr_user
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public String getCrUser() {
        return crUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_sys_user.cr_user
     *
     * @param crUser the value for vw_sys_user.cr_user
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public void setCrUser(String crUser) {
        this.crUser = crUser == null ? null : crUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_sys_user.cr_date
     *
     * @return the value of vw_sys_user.cr_date
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public Date getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_sys_user.cr_date
     *
     * @param crDate the value for vw_sys_user.cr_date
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public void setCrDate(Date crDate) {
        this.crDate = crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_sys_user.userstamp
     *
     * @return the value of vw_sys_user.userstamp
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public String getUserstamp() {
        return userstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_sys_user.userstamp
     *
     * @param userstamp the value for vw_sys_user.userstamp
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public void setUserstamp(String userstamp) {
        this.userstamp = userstamp == null ? null : userstamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_sys_user.datestamp
     *
     * @return the value of vw_sys_user.datestamp
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public Date getDatestamp() {
        return datestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_sys_user.datestamp
     *
     * @param datestamp the value for vw_sys_user.datestamp
     *
     * @mbg.generated Tue Sep 25 14:37:02 CST 2018
     */
    public void setDatestamp(Date datestamp) {
        this.datestamp = datestamp;
    }
}